/*
Copyright DHTMLX LTD. http://www.dhtmlx.com
To use this component please contact sales@dhtmlx.com to obtain license
*/
scheduler.initCustomLightbox=function(c,a,g){function k(){if(!a._lightbox){var b=a._getLightbox(),f=b.childNodes[1];b.className.indexOf("dhx_cal_light_wide")>=0?f.lastChild.firstChild.style.display="none":f.firstChild.style.display="none";f.style.height=f.style.height.replace("px","")-25+"px";b.style.height=b.style.height.replace("px","")-50+"px";b.style.width=+c.width+10+"px";f.style.width=c.width+"px"}return a._lightbox}var l=g+"_here_iframe_";a.config.buttons_left=[];a.config.buttons_right=[];
a._getLightbox=a.getLightbox;a.config.lightbox.sections=[{type:"frame",name:"box"}];a._cust_date_to_str=a.date.str_to_date("%m/%d/%Y %H:%i");a._deep_copy=function(b){if(typeof b=="object"){var a=Object.prototype.toString.call(b)=="[object Date]"?new Date(b):Object.prototype.toString.call(b)=="[object Array]"?[]:{},d;for(d in b)a[d]=scheduler._deep_copy(b[d])}else a=b;return a};c.type=="external"?(a.attachEvent("onBeforeLightbox",function(){a._custom_box_stage=0;return!0}),a.getLightbox=k,a._setLightboxValues=
function(b,f){b=document.getElementById(l);try{switch(a._custom_box_stage){case 0:if(!window.dp){var d=new DataProcessor;d.init(a)}var d=window.dp||d,e=d._getRowData(f),h="<form action='/"+c.view+"?id="+encodeURIComponent(f)+"' method='POST'>",j;for(j in e)h+="<input type='hidden' name='"+j+"'/>";h+="</form>";var i=b.Document?b.Document.body:b.contentDocument.body;i.innerHTML=h;var g=0;for(j in e)i.firstChild.childNodes[g++].value=e[j];i.firstChild.submit();break;case 1:if(!b.contentWindow.lightbox){var k=
b.contentWindow;b.contentWindow.lightbox={close:function(){a._remove_customBox()}}}a.callEvent("onLightbox",[f]);break;case 2:if(!b)return;i=b.Document?b.Document.body:b.contentDocument.body;a._doLAction(i.textContent||i.innerText);a._remove_customBox()}}catch(m){a._remove_customBox()}a._custom_box_stage++},a._remove_customBox=function(){a._lightbox?a.endLightbox(!1,a._lightbox):a.endLightbox(!1)},a._doLAction=function(b){try{var c=eval("("+b+")");if(c){var d=c.data;if(d.start_date&&d.end_date)d.start_date=
a._cust_date_to_str(c.data.start_date),d.end_date=a._cust_date_to_str(c.data.end_date);switch(c.action){case "insert":a._loading=!0;a.addEvent(d);a._loading=!1;break;case "update":var e=a.getEvent(c.sid),h;for(h in d)e[h]=d[h];a.event_updated(e);break;case "delete":a.deleteEvent(c.sid,!0)}}}catch(j){}},a.form_blocks.frame={render:function(){return"<div style='display:inline-block; height:"+c.height+"px'></div>"},set_value:function(b,f,d){a._last_id=d.id;var e='<iframe id="'+l+"\" frameborder='0' onload='"+
g+"._setLightboxValues(this, "+g+"._last_id)' src=''";if(c.width||c.height)e+=" style='";if(c.width)e+="width:"+c.width+"px;",b.style.width=c.width+"px";if(c.height)e+="height:"+c.height+"px;",b.style.height=c.height+"px";if(c.width||c.height)e+=" '";e+="><html></html></iframe>";b.innerHTML=e;if(c.classname)b.className=c.classname;return!0},get_value:function(){return!0},focus:function(){return!0}},a._addEventFromFrame=function(){var a={}}):(a.form_blocks.frame={render:function(){var a='<iframe  id="'+
g+"_here_iframe_\" onload='"+g+"._addLightboxInterface(this)' frameborder='0' src='"+c.view+"'";if(c.width||c.height)a+=" style='";c.width&&(a+="width:"+c.width+"px;");c.height&&(a+="height:"+c.height+"px;");if(c.width||c.height)a+=" '";a+=" ></iframe>";return a},set_value:function(a,c,d){if(a.contentWindow&&a.contentWindow.setValues){if(a.contentWindow.document.getElementsByTagName("form").length==1)a.contentWindow.document.getElementsByTagName("form")[0].reset();else{var d=a.contentWindow.getValues(),
e;for(e in d)d[e]="";a.contentWindow.setValues(d)}a.contentWindow.setValues(d)}},get_value:function(b){return a._deep_copy(b.contentWindow.getValues())},focus:function(){return!0}},a.getLightbox=k,a._addLightboxInterface=function(b){if(!b.contentWindow.lightbox)b.contentWindow.lightbox={};b.contentWindow.lightbox.save=function(){var c=a.getEvent(a.getState().lightbox_id),d=b.contentWindow.getValues(),f;for(f in d)c[f]=d[f];a.endLightbox(!0,a._lightbox)};b.contentWindow.lightbox.close=function(){a.endLightbox(!1,
a._lightbox)};b.contentWindow.lightbox.remove=function(){var b=a.locale.labels.confirm_deleting;if(!b||confirm(b))a.deleteEvent(a._lightbox_id),a._new_event=null;a.endLightbox(!0,a._lightbox)};if(b.contentWindow.document.getElementsByTagName("form").length==1)b.contentWindow.document.getElementsByTagName("form")[0].reset();else{var c=b.contentWindow.getValues(),d;for(d in c)c[d]="";b.contentWindow.setValues(c)}b.contentWindow.setValues(a.getEvent(a._lightbox_id));a.callEvent("onLightbox",[a._lightbox_id])})};
