/*
Copyright DHTMLX LTD. http://www.dhtmlx.com
To use this component please contact sales@dhtmlx.com to obtain license
*/
window.dhtmlx||(dhtmlx=function(a){for(var e in a)dhtmlx[e]=a[e];return dhtmlx});
dhtmlx.extend_api=function(a,e,b){var d=window[a];if(d)window[a]=function(b){if(b&&typeof b=="object"&&!b.tagName){var a=d.apply(this,e._init?e._init(b):arguments),g;for(g in dhtmlx)if(e[g])this[e[g]](dhtmlx[g]);for(g in b)if(e[g])this[e[g]](b[g]);else g.indexOf("on")==0&&this.attachEvent(g,b[g])}else a=d.apply(this,arguments);e._patch&&e._patch(this);return a||this},window[a].prototype=d.prototype,b&&dhtmlXHeir(window[a].prototype,b)};
dhtmlxAjax={get:function(a,e){var b=new dtmlXMLLoaderObject(!0);b.async=arguments.length<3;b.waitCall=e;b.loadXML(a);return b},post:function(a,e,b){var d=new dtmlXMLLoaderObject(!0);d.async=arguments.length<4;d.waitCall=b;d.loadXML(a,!0,e);return d},getSync:function(a){return this.get(a,null,!0)},postSync:function(a,e){return this.post(a,e,null,!0)}};
function dtmlXMLLoaderObject(a,e,b,d){this.xmlDoc="";this.async=typeof b!="undefined"?b:!0;this.onloadAction=a||null;this.mainObject=e||null;this.waitCall=null;this.rSeed=d||!1;return this}dtmlXMLLoaderObject.count=0;
dtmlXMLLoaderObject.prototype.waitLoadFunction=function(a){var e=!0;return this.check=function(){if(a&&a.onloadAction!=null&&(!a.xmlDoc.readyState||a.xmlDoc.readyState==4)&&e){e=!1;dtmlXMLLoaderObject.count++;if(typeof a.onloadAction=="function")a.onloadAction(a.mainObject,null,null,null,a);if(a.waitCall)a.waitCall.call(this,a),a.waitCall=null}}};
dtmlXMLLoaderObject.prototype.getXMLTopNode=function(a,e){if(this.xmlDoc.responseXML){var b=this.xmlDoc.responseXML.getElementsByTagName(a);b.length==0&&a.indexOf(":")!=-1&&(b=this.xmlDoc.responseXML.getElementsByTagName(a.split(":")[1]));var d=b[0]}else d=this.xmlDoc.documentElement;if(d)return this._retry=!1,d;if(!this._retry)return this._retry=!0,e=this.xmlDoc,this.loadXMLString(this.xmlDoc.responseText.replace(/^[\s]+/,""),!0),this.getXMLTopNode(a,e);dhtmlxError.throwError("LoadXML","Incorrect XML",
[e||this.xmlDoc,this.mainObject]);return document.createElement("DIV")};dtmlXMLLoaderObject.prototype.loadXMLString=function(a,e){if(_isIE)this.xmlDoc=new ActiveXObject("Microsoft.XMLDOM"),this.xmlDoc.async=this.async,this.xmlDoc.onreadystatechange=function(){},this.xmlDoc.loadXML(a);else{var b=new DOMParser;this.xmlDoc=b.parseFromString(a,"text/xml")}if(!e){if(this.onloadAction)this.onloadAction(this.mainObject,null,null,null,this);if(this.waitCall)this.waitCall(),this.waitCall=null}};
dtmlXMLLoaderObject.prototype.loadXML=function(a,e,b,d){this.rSeed&&(a+=(a.indexOf("?")!=-1?"&":"?")+"a_dhx_rSeed="+(new Date).valueOf());this.filePath=a;this.xmlDoc=!_isIE&&window.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Microsoft.XMLHTTP");if(this.async)this.xmlDoc.onreadystatechange=new this.waitLoadFunction(this);this.xmlDoc.open(e?"POST":"GET",a,this.async);d?(this.xmlDoc.setRequestHeader("User-Agent","dhtmlxRPC v0.1 ("+navigator.userAgent+")"),this.xmlDoc.setRequestHeader("Content-type",
"text/xml")):e&&this.xmlDoc.setRequestHeader("Content-type","application/x-www-form-urlencoded");this.xmlDoc.setRequestHeader("X-Requested-With","XMLHttpRequest");this.xmlDoc.send(b);this.async||(new this.waitLoadFunction(this))()};
dtmlXMLLoaderObject.prototype.destructor=function(){return this.setXSLParamValue=this.getXMLTopNode=this.xmlNodeToJSON=this.doSerialization=this.loadXMLString=this.loadXML=this.doXSLTransToString=this.doXSLTransToObject=this.doXPathOpera=this.doXPath=this.xmlDoc=this.mainObject=this.onloadAction=this.filePath=this.rSeed=this.async=this._retry=this._getAllNamedChilds=this._filterXPath=null};
dtmlXMLLoaderObject.prototype.xmlNodeToJSON=function(a){for(var e={},b=0;b<a.attributes.length;b++)e[a.attributes[b].name]=a.attributes[b].value;e._tagvalue=a.firstChild?a.firstChild.nodeValue:"";for(b=0;b<a.childNodes.length;b++){var d=a.childNodes[b].tagName;d&&(e[d]||(e[d]=[]),e[d].push(this.xmlNodeToJSON(a.childNodes[b])))}return e};function callerFunction(a,e){return this.handler=function(b){if(!b)b=window.event;a(b,e);return!0}}function getAbsoluteLeft(a){return getOffset(a).left}
function getAbsoluteTop(a){return getOffset(a).top}function getOffsetSum(a){for(var e=0,b=0;a;)e+=parseInt(a.offsetTop),b+=parseInt(a.offsetLeft),a=a.offsetParent;return{top:e,left:b}}
function getOffsetRect(a){var e=a.getBoundingClientRect(),b=document.body,d=document.documentElement,c=window.pageYOffset||d.scrollTop||b.scrollTop,h=window.pageXOffset||d.scrollLeft||b.scrollLeft,g=d.clientTop||b.clientTop||0,f=d.clientLeft||b.clientLeft||0,i=e.top+c-g,j=e.left+h-f;return{top:Math.round(i),left:Math.round(j)}}function getOffset(a){return a.getBoundingClientRect?getOffsetRect(a):getOffsetSum(a)}
function convertStringToBoolean(a){typeof a=="string"&&(a=a.toLowerCase());switch(a){case "1":case "true":case "yes":case "y":case 1:case !0:return!0;default:return!1}}function getUrlSymbol(a){return a.indexOf("?")!=-1?"&":"?"}function dhtmlDragAndDropObject(){if(window.dhtmlDragAndDrop)return window.dhtmlDragAndDrop;this.dragStartObject=this.dragStartNode=this.dragNode=this.lastLanding=0;this.tempDOMM=this.tempDOMU=null;this.waitDrag=0;window.dhtmlDragAndDrop=this;return this}
dhtmlDragAndDropObject.prototype.removeDraggableItem=function(a){a.onmousedown=null;a.dragStarter=null;a.dragLanding=null};dhtmlDragAndDropObject.prototype.addDraggableItem=function(a,e){a.onmousedown=this.preCreateDragCopy;a.dragStarter=e;this.addDragLanding(a,e)};dhtmlDragAndDropObject.prototype.addDragLanding=function(a,e){a.dragLanding=e};
dhtmlDragAndDropObject.prototype.preCreateDragCopy=function(a){if(!((a||window.event)&&(a||event).button==2)){if(window.dhtmlDragAndDrop.waitDrag)return window.dhtmlDragAndDrop.waitDrag=0,document.body.onmouseup=window.dhtmlDragAndDrop.tempDOMU,document.body.onmousemove=window.dhtmlDragAndDrop.tempDOMM,!1;window.dhtmlDragAndDrop.dragNode&&window.dhtmlDragAndDrop.stopDrag(a);window.dhtmlDragAndDrop.waitDrag=1;window.dhtmlDragAndDrop.tempDOMU=document.body.onmouseup;window.dhtmlDragAndDrop.tempDOMM=
document.body.onmousemove;window.dhtmlDragAndDrop.dragStartNode=this;window.dhtmlDragAndDrop.dragStartObject=this.dragStarter;document.body.onmouseup=window.dhtmlDragAndDrop.preCreateDragCopy;document.body.onmousemove=window.dhtmlDragAndDrop.callDrag;window.dhtmlDragAndDrop.downtime=(new Date).valueOf();a&&a.preventDefault&&a.preventDefault();return!1}};
dhtmlDragAndDropObject.prototype.callDrag=function(a){if(!a)a=window.event;dragger=window.dhtmlDragAndDrop;if(!((new Date).valueOf()-dragger.downtime<100)){if(!dragger.dragNode)if(dragger.waitDrag){dragger.dragNode=dragger.dragStartObject._createDragNode(dragger.dragStartNode,a);if(!dragger.dragNode)return dragger.stopDrag();dragger.dragNode.onselectstart=function(){return!1};dragger.gldragNode=dragger.dragNode;document.body.appendChild(dragger.dragNode);document.body.onmouseup=dragger.stopDrag;dragger.waitDrag=
0;dragger.dragNode.pWindow=window;dragger.initFrameRoute()}else return dragger.stopDrag(a,!0);if(dragger.dragNode.parentNode!=window.document.body&&dragger.gldragNode){var e=dragger.gldragNode;if(dragger.gldragNode.old)e=dragger.gldragNode.old;e.parentNode.removeChild(e);var b=dragger.dragNode.pWindow;e.pWindow&&e.pWindow.dhtmlDragAndDrop.lastLanding&&e.pWindow.dhtmlDragAndDrop.lastLanding.dragLanding._dragOut(e.pWindow.dhtmlDragAndDrop.lastLanding);if(_isIE){var d=document.createElement("Div");d.innerHTML=
dragger.dragNode.outerHTML;dragger.dragNode=d.childNodes[0]}else dragger.dragNode=dragger.dragNode.cloneNode(!0);dragger.dragNode.pWindow=window;dragger.gldragNode.old=dragger.dragNode;document.body.appendChild(dragger.dragNode);b.dhtmlDragAndDrop.dragNode=dragger.dragNode}dragger.dragNode.style.left=a.clientX+15+(dragger.fx?dragger.fx*-1:0)+(document.body.scrollLeft||document.documentElement.scrollLeft)+"px";dragger.dragNode.style.top=a.clientY+3+(dragger.fy?dragger.fy*-1:0)+(document.body.scrollTop||
document.documentElement.scrollTop)+"px";var c=a.srcElement?a.srcElement:a.target;dragger.checkLanding(c,a)}};dhtmlDragAndDropObject.prototype.calculateFramePosition=function(a){if(window.name){for(var e=parent.frames[window.name].frameElement.offsetParent,b=0,d=0;e;)b+=e.offsetLeft,d+=e.offsetTop,e=e.offsetParent;if(parent.dhtmlDragAndDrop){var c=parent.dhtmlDragAndDrop.calculateFramePosition(1);b+=c.split("_")[0]*1;d+=c.split("_")[1]*1}if(a)return b+"_"+d;else this.fx=b;this.fy=d}return"0_0"};
dhtmlDragAndDropObject.prototype.checkLanding=function(a,e){a&&a.dragLanding?(this.lastLanding&&this.lastLanding.dragLanding._dragOut(this.lastLanding),this.lastLanding=a,this.lastLanding=this.lastLanding.dragLanding._dragIn(this.lastLanding,this.dragStartNode,e.clientX,e.clientY,e),this.lastLanding_scr=_isIE?e.srcElement:e.target):a&&a.tagName!="BODY"?this.checkLanding(a.parentNode,e):(this.lastLanding&&this.lastLanding.dragLanding._dragOut(this.lastLanding,e.clientX,e.clientY,e),this.lastLanding=
0,this._onNotFound&&this._onNotFound())};
dhtmlDragAndDropObject.prototype.stopDrag=function(a,e){dragger=window.dhtmlDragAndDrop;if(!e){dragger.stopFrameRoute();var b=dragger.lastLanding;dragger.lastLanding=null;b&&b.dragLanding._drag(dragger.dragStartNode,dragger.dragStartObject,b,_isIE?event.srcElement:a.target)}dragger.lastLanding=null;dragger.dragNode&&dragger.dragNode.parentNode==document.body&&dragger.dragNode.parentNode.removeChild(dragger.dragNode);dragger.dragNode=0;dragger.gldragNode=0;dragger.fx=0;dragger.fy=0;dragger.dragStartNode=
0;dragger.dragStartObject=0;document.body.onmouseup=dragger.tempDOMU;document.body.onmousemove=dragger.tempDOMM;dragger.tempDOMU=null;dragger.tempDOMM=null;dragger.waitDrag=0};dhtmlDragAndDropObject.prototype.stopFrameRoute=function(a){a&&window.dhtmlDragAndDrop.stopDrag(1,1);for(var e=0;e<window.frames.length;e++)try{window.frames[e]!=a&&window.frames[e].dhtmlDragAndDrop&&window.frames[e].dhtmlDragAndDrop.stopFrameRoute(window)}catch(b){}try{parent.dhtmlDragAndDrop&&parent!=window&&parent!=a&&parent.dhtmlDragAndDrop.stopFrameRoute(window)}catch(d){}};
dhtmlDragAndDropObject.prototype.initFrameRoute=function(a,e){if(a)window.dhtmlDragAndDrop.preCreateDragCopy(),window.dhtmlDragAndDrop.dragStartNode=a.dhtmlDragAndDrop.dragStartNode,window.dhtmlDragAndDrop.dragStartObject=a.dhtmlDragAndDrop.dragStartObject,window.dhtmlDragAndDrop.dragNode=a.dhtmlDragAndDrop.dragNode,window.dhtmlDragAndDrop.gldragNode=a.dhtmlDragAndDrop.dragNode,window.document.body.onmouseup=window.dhtmlDragAndDrop.stopDrag,window.waitDrag=0,!_isIE&&e&&(!_isFF||_FFrv<1.8)&&window.dhtmlDragAndDrop.calculateFramePosition();
try{parent.dhtmlDragAndDrop&&parent!=window&&parent!=a&&parent.dhtmlDragAndDrop.initFrameRoute(window)}catch(b){}for(var d=0;d<window.frames.length;d++)try{window.frames[d]!=a&&window.frames[d].dhtmlDragAndDrop&&window.frames[d].dhtmlDragAndDrop.initFrameRoute(window,!a||e?1:0)}catch(c){}};_OperaRv=_KHTMLrv=_FFrv=_isChrome=_isMacOS=_isKHTML=_isOpera=_isIE=_isFF=!1;navigator.userAgent.indexOf("Macintosh")!=-1&&(_isMacOS=!0);navigator.userAgent.toLowerCase().indexOf("chrome")>-1&&(_isChrome=!0);
if(navigator.userAgent.indexOf("Safari")!=-1||navigator.userAgent.indexOf("Konqueror")!=-1)_KHTMLrv=parseFloat(navigator.userAgent.substr(navigator.userAgent.indexOf("Safari")+7,5)),_KHTMLrv>525?(_isFF=!0,_FFrv=1.9):_isKHTML=!0;else if(navigator.userAgent.indexOf("Opera")!=-1)_isOpera=!0,_OperaRv=parseFloat(navigator.userAgent.substr(navigator.userAgent.indexOf("Opera")+6,3));else if(navigator.appName.indexOf("Microsoft")!=-1){if(_isIE=!0,(navigator.appVersion.indexOf("MSIE 8.0")!=-1||navigator.appVersion.indexOf("MSIE 9.0")!=
-1||navigator.appVersion.indexOf("MSIE 10.0")!=-1)&&document.compatMode!="BackCompat")_isIE=8}else _isFF=!0,_FFrv=parseFloat(navigator.userAgent.split("rv:")[1]);
dtmlXMLLoaderObject.prototype.doXPath=function(a,e,b,d){if(_isKHTML||!_isIE&&!window.XPathResult)return this.doXPathOpera(a,e);if(_isIE)return e||(e=this.xmlDoc.nodeName?this.xmlDoc:this.xmlDoc.responseXML),e||dhtmlxError.throwError("LoadXML","Incorrect XML",[e||this.xmlDoc,this.mainObject]),b!=null&&e.setProperty("SelectionNamespaces","xmlns:xsl='"+b+"'"),d=="single"?e.selectSingleNode(a):e.selectNodes(a)||[];else{var c=e;e||(e=this.xmlDoc.nodeName?this.xmlDoc:this.xmlDoc.responseXML);e||dhtmlxError.throwError("LoadXML",
"Incorrect XML",[e||this.xmlDoc,this.mainObject]);e.nodeName.indexOf("document")!=-1?c=e:(c=e,e=e.ownerDocument);var h=XPathResult.ANY_TYPE;if(d=="single")h=XPathResult.FIRST_ORDERED_NODE_TYPE;var g=[],f=e.evaluate(a,c,function(){return b},h,null);if(h==XPathResult.FIRST_ORDERED_NODE_TYPE)return f.singleNodeValue;for(var i=f.iterateNext();i;)g[g.length]=i,i=f.iterateNext();return g}};function x(){if(!this.catches)this.catches=[];return this}x.prototype.catchError=function(a,e){this.catches[a]=e};
x.prototype.throwError=function(a,e,b){if(this.catches[a])return this.catches[a](a,e,b);if(this.catches.ALL)return this.catches.ALL(a,e,b);alert("Error type: "+a+"\nDescription: "+e);return null};window.dhtmlxError=new x;
dtmlXMLLoaderObject.prototype.doXPathOpera=function(a,e){var b=a.replace(/[\/]+/gi,"/").split("/"),d=null,c=1;if(!b.length)return[];if(b[0]==".")d=[e];else if(b[0]=="")d=(this.xmlDoc.responseXML||this.xmlDoc).getElementsByTagName(b[c].replace(/\[[^\]]*\]/g,"")),c++;else return[];for(;c<b.length;c++)d=this._getAllNamedChilds(d,b[c]);b[c-1].indexOf("[")!=-1&&(d=this._filterXPath(d,b[c-1]));return d};
dtmlXMLLoaderObject.prototype._filterXPath=function(a,e){for(var b=[],e=e.replace(/[^\[]*\[\@/g,"").replace(/[\[\]\@]*/g,""),d=0;d<a.length;d++)a[d].getAttribute(e)&&(b[b.length]=a[d]);return b};
dtmlXMLLoaderObject.prototype._getAllNamedChilds=function(a,e){var b=[];_isKHTML&&(e=e.toUpperCase());for(var d=0;d<a.length;d++)for(var c=0;c<a[d].childNodes.length;c++)_isKHTML?a[d].childNodes[c].tagName&&a[d].childNodes[c].tagName.toUpperCase()==e&&(b[b.length]=a[d].childNodes[c]):a[d].childNodes[c].tagName==e&&(b[b.length]=a[d].childNodes[c]);return b};function dhtmlXHeir(a,e){for(var b in e)typeof e[b]=="function"&&(a[b]=e[b]);return a}
function dhtmlxEvent(a,e,b){a.addEventListener?a.addEventListener(e,b,!1):a.attachEvent&&a.attachEvent("on"+e,b)}dtmlXMLLoaderObject.prototype.xslDoc=null;dtmlXMLLoaderObject.prototype.setXSLParamValue=function(a,e,b){if(!b)b=this.xslDoc;if(b.responseXML)b=b.responseXML;var d=this.doXPath("/xsl:stylesheet/xsl:variable[@name='"+a+"']",b,"http://www.w3.org/1999/XSL/Transform","single");if(d!=null)d.firstChild.nodeValue=e};
dtmlXMLLoaderObject.prototype.doXSLTransToObject=function(a,e){if(!a)a=this.xslDoc;if(a.responseXML)a=a.responseXML;if(!e)e=this.xmlDoc;if(e.responseXML)e=e.responseXML;if(_isIE){d=new ActiveXObject("Msxml2.DOMDocument.3.0");try{e.transformNodeToObject(a,d)}catch(b){d=e.transformNode(a)}}else{if(!this.XSLProcessor)this.XSLProcessor=new XSLTProcessor,this.XSLProcessor.importStylesheet(a);var d=this.XSLProcessor.transformToDocument(e)}return d};
dtmlXMLLoaderObject.prototype.doXSLTransToString=function(a,e){var b=this.doXSLTransToObject(a,e);return typeof b=="string"?b:this.doSerialization(b)};dtmlXMLLoaderObject.prototype.doSerialization=function(a){if(!a)a=this.xmlDoc;if(a.responseXML)a=a.responseXML;if(_isIE)return a.xml;else{var e=new XMLSerializer;return e.serializeToString(a)}};
dhtmlxEventable=function(a){a.attachEvent=function(a,b,d){a="ev_"+a.toLowerCase();this[a]||(this[a]=new this.eventCatcher(d||this));return a+":"+this[a].addEvent(b)};a.callEvent=function(a,b){a="ev_"+a.toLowerCase();return this[a]?this[a].apply(this,b):!0};a.checkEvent=function(a){return!!this["ev_"+a.toLowerCase()]};a.eventCatcher=function(a){var b=[],d=function(){for(var d=!0,h=0;h<b.length;h++)if(b[h]!=null)var g=b[h].apply(a,arguments),d=d&&g;return d};d.addEvent=function(a){typeof a!="function"&&
(a=eval(a));return a?b.push(a)-1:!1};d.removeEvent=function(a){b[a]=null};return d};a.detachEvent=function(a){if(a!=!1){var b=a.split(":");this[b[0]].removeEvent(b[1])}};a.detachAllEvents=function(){for(var a in this)a.indexOf("ev_")==0&&delete this[a]};a=null};if(!window.dhtmlx)window.dhtmlx={};
(function(){function a(a,d){var c=a.callback;b(!1);a.box.parentNode.removeChild(a.box);m=a.box=null;c&&c(d)}function e(b){if(m){var b=b||event,d=b.which||event.keyCode;dhtmlx.message.keyboard&&((d==13||d==32)&&a(m,!0),d==27&&a(m,!1));b.preventDefault&&b.preventDefault();return!(b.cancelBubble=!0)}}function b(a){if(!b.cover)b.cover=document.createElement("DIV"),b.cover.onkeydown=e,b.cover.className="dhx_modal_cover",document.body.appendChild(b.cover);var d=document.body.scrollHeight;b.cover.style.display=
a?"inline-block":"none"}function d(b,a){var d="dhtmlx_"+b.toLowerCase().replace(/ /g,"_")+"_button";return"<div class='dhtmlx_popup_button "+d+"' result='"+a+"' ><div>"+b+"</div></div>"}function c(b){if(!l.area)l.area=document.createElement("DIV"),l.area.className="dhtmlx_message_area",l.area.style[l.position]="5px",document.body.appendChild(l.area);l.hide(b.id);var a=document.createElement("DIV");a.innerHTML="<div>"+b.text+"</div>";a.className="dhtmlx-info dhtmlx-"+b.type;a.onclick=function(){l.hide(b.id);
b=null};l.position=="bottom"&&l.area.firstChild?l.area.insertBefore(a,l.area.firstChild):l.area.appendChild(a);b.expire>0&&(l.timers[b.id]=window.setTimeout(function(){l.hide(b.id)},b.expire));l.pull[b.id]=a;a=null;return b.id}function h(b,c,h){var g=document.createElement("DIV");g.className=" dhtmlx_modal_box dhtmlx-"+b.type;g.setAttribute("dhxbox",1);var f="";if(b.width)g.style.width=b.width;if(b.height)g.style.height=b.height;b.title&&(f+='<div class="dhtmlx_popup_title">'+b.title+"</div>");f+=
'<div class="dhtmlx_popup_text"><span>'+(b.content?"":b.text)+'</span></div><div  class="dhtmlx_popup_controls">';c&&(f+=d(b.ok||"OK",!0));h&&(f+=d(b.cancel||"Cancel",!1));if(b.buttons)for(var e=0;e<b.buttons.length;e++)f+=d(b.buttons[e],e);f+="</div>";g.innerHTML=f;if(b.content){var i=b.content;typeof i=="string"&&(i=document.getElementById(i));if(i.style.display=="none")i.style.display="";g.childNodes[b.title?1:0].appendChild(i)}g.onclick=function(d){var d=d||event,c=d.target||d.srcElement;if(!c.className)c=
c.parentNode;c.className.split(" ")[0]=="dhtmlx_popup_button"&&(result=c.getAttribute("result"),result=result=="true"||(result=="false"?!1:result),a(b,result))};b.box=g;if(c||h)m=b;return g}function g(a,d,c){var g=a.tagName?a:h(a,d,c);a.hidden||b(!0);document.body.appendChild(g);var f=Math.abs(Math.floor(((window.innerWidth||document.documentElement.offsetWidth)-g.offsetWidth)/2)),i=Math.abs(Math.floor(((window.innerHeight||document.documentElement.offsetHeight)-g.offsetHeight)/2));g.style.top=a.position==
"top"?"-3px":i+"px";g.style.left=f+"px";g.onkeydown=e;g.focus();a.hidden&&dhtmlx.modalbox.hide(g);return g}function f(b){return g(b,!0,!1)}function i(b){return g(b,!0,!0)}function j(b){return g(b)}function n(b,a,d){typeof b!="object"&&(typeof a=="function"&&(d=a,a=""),b={text:b,type:a,callback:d});return b}function k(b,a,d,c){typeof b!="object"&&(b={text:b,type:a,expire:d,id:c});b.id=b.id||l.uid();b.expire=b.expire||l.expire;return b}var m=null;document.attachEvent?document.attachEvent("onkeydown",
e):document.addEventListener("keydown",e,!0);dhtmlx.alert=function(){text=n.apply(this,arguments);text.type=text.type||"confirm";return f(text)};dhtmlx.confirm=function(){text=n.apply(this,arguments);text.type=text.type||"alert";return i(text)};dhtmlx.modalbox=function(){text=n.apply(this,arguments);text.type=text.type||"alert";return j(text)};dhtmlx.modalbox.hide=function(a){for(;a&&a.getAttribute&&!a.getAttribute("dhxbox");)a=a.parentNode;a&&(a.parentNode.removeChild(a),b(!1))};var l=dhtmlx.message=
function(b,a,d,h){b=k.apply(this,arguments);b.type=b.type||"info";var g=b.type.split("-")[0];switch(g){case "alert":return f(b);case "confirm":return i(b);case "modalbox":return j(b);default:return c(b)}};l.seed=(new Date).valueOf();l.uid=function(){return l.seed++};l.expire=4E3;l.keyboard=!0;l.position="top";l.pull={};l.timers={};l.hideAll=function(){for(var b in l.pull)l.hide(b)};l.hide=function(b){var a=l.pull[b];a&&a.parentNode&&(window.setTimeout(function(){a.parentNode.removeChild(a);a=null},
2E3),a.className+=" hidden",l.timers[b]&&window.clearTimeout(l.timers[b]),delete l.pull[b])}})();
function dataProcessor(a){this.serverProcessor=a;this.action_param="!nativeeditor_status";this.object=null;this.updatedRows=[];this.autoUpdate=!0;this.updateMode="cell";this._tMode="GET";this.post_delim="_";this._waitMode=0;this._in_progress={};this._invalid={};this.mandatoryFields=[];this.messages=[];this.styles={updated:"font-weight:bold;",inserted:"font-weight:bold;",deleted:"text-decoration : line-through;",invalid:"background-color:FFE0E0;",invalid_cell:"border-bottom:2px solid red;",error:"color:red;",
clear:"font-weight:normal;text-decoration:none;"};this.enableUTFencoding(!0);dhtmlxEventable(this);return this}
dataProcessor.prototype={setTransactionMode:function(a,e){this._tMode=a;this._tSend=e},escape:function(a){return this._utf?encodeURIComponent(a):escape(a)},enableUTFencoding:function(a){this._utf=convertStringToBoolean(a)},setDataColumns:function(a){this._columns=typeof a=="string"?a.split(","):a},getSyncState:function(){return!this.updatedRows.length},enableDataNames:function(a){this._endnm=convertStringToBoolean(a)},enablePartialDataSend:function(a){this._changed=convertStringToBoolean(a)},setUpdateMode:function(a,
e){this.autoUpdate=a=="cell";this.updateMode=a;this.dnd=e},ignore:function(a,e){this._silent_mode=!0;a.call(e||window);this._silent_mode=!1},setUpdated:function(a,e,b){if(!this._silent_mode){var d=this.findRow(a),b=b||"updated",c=this.obj.getUserData(a,this.action_param);c&&b=="updated"&&(b=c);e?(this.set_invalid(a,!1),this.updatedRows[d]=a,this.obj.setUserData(a,this.action_param,b),this._in_progress[a]&&(this._in_progress[a]="wait")):this.is_invalid(a)||(this.updatedRows.splice(d,1),this.obj.setUserData(a,
this.action_param,""));e||this._clearUpdateFlag(a);this.markRow(a,e,b);e&&this.autoUpdate&&this.sendData(a)}},_clearUpdateFlag:function(){},markRow:function(a,e,b){var d="",c=this.is_invalid(a);c&&(d=this.styles[c],e=!0);if(this.callEvent("onRowMark",[a,e,b,c])&&(d=this.styles[e?b:"clear"]+d,this.obj[this._methods[0]](a,d),c&&c.details)){d+=this.styles[c+"_cell"];for(var h=0;h<c.details.length;h++)if(c.details[h])this.obj[this._methods[1]](a,h,d)}},getState:function(a){return this.obj.getUserData(a,
this.action_param)},is_invalid:function(a){return this._invalid[a]},set_invalid:function(a,e,b){b&&(e={value:e,details:b,toString:function(){return this.value.toString()}});this._invalid[a]=e},checkBeforeUpdate:function(){return!0},sendData:function(a){if(!this._waitMode||!(this.obj.mytype=="tree"||this.obj._h2)){this.obj.editStop&&this.obj.editStop();if(typeof a=="undefined"||this._tSend)return this.sendAllData();if(this._in_progress[a])return!1;this.messages=[];if(!this.checkBeforeUpdate(a)&&this.callEvent("onValidatationError",
[a,this.messages]))return!1;this._beforeSendData(this._getRowData(a),a)}},_beforeSendData:function(a,e){if(!this.callEvent("onBeforeUpdate",[e,this.getState(e),a]))return!1;this._sendData(a,e)},serialize:function(a,e){if(typeof a=="string")return a;if(typeof e!="undefined")return this.serialize_one(a,"");else{var b=[],d=[],c;for(c in a)a.hasOwnProperty(c)&&(b.push(this.serialize_one(a[c],c+this.post_delim)),d.push(c));b.push("ids="+this.escape(d.join(",")));dhtmlx.security_key&&b.push("dhx_security="+
dhtmlx.security_key);return b.join("&")}},serialize_one:function(a,e){if(typeof a=="string")return a;var b=[],d;for(d in a)a.hasOwnProperty(d)&&b.push(this.escape((e||"")+d)+"="+this.escape(a[d]));return b.join("&")},_sendData:function(a,e){if(a){if(!this.callEvent("onBeforeDataSending",e?[e,this.getState(e),a]:[null,null,a]))return!1;e&&(this._in_progress[e]=(new Date).valueOf());var b=new dtmlXMLLoaderObject(this.afterUpdate,this,!0),d=this.serverProcessor+(this._user?getUrlSymbol(this.serverProcessor)+
["dhx_user="+this._user,"dhx_version="+this.obj.getUserData(0,"version")].join("&"):"");this._tMode!="POST"?b.loadXML(d+(d.indexOf("?")!=-1?"&":"?")+this.serialize(a,e)):b.loadXML(d,!0,this.serialize(a,e));this._waitMode++}},sendAllData:function(){if(this.updatedRows.length){this.messages=[];for(var a=!0,e=0;e<this.updatedRows.length;e++)a&=this.checkBeforeUpdate(this.updatedRows[e]);if(!a&&!this.callEvent("onValidatationError",["",this.messages]))return!1;if(this._tSend)this._sendData(this._getAllData());
else for(e=0;e<this.updatedRows.length;e++)if(!this._in_progress[this.updatedRows[e]]&&!this.is_invalid(this.updatedRows[e])&&(this._beforeSendData(this._getRowData(this.updatedRows[e]),this.updatedRows[e]),this._waitMode&&(this.obj.mytype=="tree"||this.obj._h2)))break}},_getAllData:function(){for(var a={},e=!1,b=0;b<this.updatedRows.length;b++){var d=this.updatedRows[b];!this._in_progress[d]&&!this.is_invalid(d)&&this.callEvent("onBeforeUpdate",[d,this.getState(d)])&&(a[d]=this._getRowData(d,d+this.post_delim),
e=!0,this._in_progress[d]=(new Date).valueOf())}return e?a:null},setVerificator:function(a,e){this.mandatoryFields[a]=e||function(b){return b!=""}},clearVerificator:function(a){this.mandatoryFields[a]=!1},findRow:function(a){for(var e=0,e=0;e<this.updatedRows.length;e++)if(a==this.updatedRows[e])break;return e},defineAction:function(a,e){if(!this._uActions)this._uActions=[];this._uActions[a]=e},afterUpdateCallback:function(a,e,b,d){var c=a,h=b!="error"&&b!="invalid";h||this.set_invalid(a,b);if(this._uActions&&
this._uActions[b]&&!this._uActions[b](d))return delete this._in_progress[c];this._in_progress[c]!="wait"&&this.setUpdated(a,!1);var g=a;switch(b){case "update":case "updated":case "inserted":case "insert":e!=a&&(this.obj[this._methods[2]](a,e),a=e);break;case "delete":case "deleted":return this.obj.setUserData(a,this.action_param,"true_deleted"),this.obj[this._methods[3]](a),delete this._in_progress[c],this.callEvent("onAfterUpdate",[a,b,e,d])}this._in_progress[c]!="wait"?(h&&this.obj.setUserData(a,
this.action_param,""),delete this._in_progress[c]):(delete this._in_progress[c],this.setUpdated(e,!0,this.obj.getUserData(a,this.action_param)));this.callEvent("onAfterUpdate",[a,b,e,d])},afterUpdate:function(a,e,b,d,c){c.getXMLTopNode("data");if(c.xmlDoc.responseXML){for(var h=c.doXPath("//data/action"),g=0;g<h.length;g++){var f=h[g],i=f.getAttribute("type"),j=f.getAttribute("sid"),n=f.getAttribute("tid");a.afterUpdateCallback(j,n,i,f)}a.finalizeUpdate()}},finalizeUpdate:function(){this._waitMode&&
this._waitMode--;(this.obj.mytype=="tree"||this.obj._h2)&&this.updatedRows.length&&this.sendData();this.callEvent("onAfterUpdateFinish",[]);this.updatedRows.length||this.callEvent("onFullSync",[])},init:function(a){this.obj=a;this.obj._dp_init&&this.obj._dp_init(this)},setOnAfterUpdate:function(a){this.attachEvent("onAfterUpdate",a)},enableDebug:function(){},setOnBeforeUpdateHandler:function(a){this.attachEvent("onBeforeDataSending",a)},setAutoUpdate:function(a,e){a=a||2E3;this._user=e||(new Date).valueOf();
this._need_update=!1;this._loader=null;this._update_busy=!1;this.attachEvent("onAfterUpdate",function(b,a,h,g){this.afterAutoUpdate(b,a,h,g)});this.attachEvent("onFullSync",function(){this.fullSync()});var b=this;window.setInterval(function(){b.loadUpdate()},a)},afterAutoUpdate:function(a,e){return e=="collision"?(this._need_update=!0,!1):!0},fullSync:function(){if(this._need_update==!0)this._need_update=!1,this.loadUpdate();return!0},getUpdates:function(a,e){if(this._update_busy)return!1;else this._update_busy=
!0;this._loader=this._loader||new dtmlXMLLoaderObject(!0);this._loader.async=!0;this._loader.waitCall=e;this._loader.loadXML(a)},_v:function(a){return a.firstChild?a.firstChild.nodeValue:""},_a:function(a){for(var e=[],b=0;b<a.length;b++)e[b]=this._v(a[b]);return e},loadUpdate:function(){var a=this,e=this.obj.getUserData(0,"version"),b=this.serverProcessor+getUrlSymbol(this.serverProcessor)+["dhx_user="+this._user,"dhx_version="+e].join("&"),b=b.replace("editing=true&","");this.getUpdates(b,function(){var b=
a._loader.doXPath("//userdata");a.obj.setUserData(0,"version",a._v(b[0]));var c=a._loader.doXPath("//update");if(c.length){a._silent_mode=!0;for(var h=0;h<c.length;h++){var g=c[h].getAttribute("status"),f=c[h].getAttribute("id"),e=c[h].getAttribute("parent");switch(g){case "inserted":a.callEvent("insertCallback",[c[h],f,e]);break;case "updated":a.callEvent("updateCallback",[c[h],f,e]);break;case "deleted":a.callEvent("deleteCallback",[c[h],f,e])}}a._silent_mode=!1}a._update_busy=!1;a=null})}};
if(window.dhtmlXGridObject)dhtmlXGridObject.prototype._init_point_connector=dhtmlXGridObject.prototype._init_point,dhtmlXGridObject.prototype._init_point=function(){var a=function(b){b=b.replace(/(\?|\&)connector[^\f]*/g,"");return b+(b.indexOf("?")!=-1?"&":"?")+"connector=true"+(this.hdr.rows.length>0?"&dhx_no_header=1":"")},e=function(b){return a.call(this,b)+(this._connector_sorting||"")+(this._connector_filter||"")},b=function(b,a,d){this._connector_sorting="&dhx_sort["+a+"]="+d;return e.call(this,
b)},d=function(b,a,d){for(var f=0;f<a.length;f++)a[f]="dhx_filter["+a[f]+"]="+encodeURIComponent(d[f]);this._connector_filter="&"+a.join("&");return e.call(this,b)};this.attachEvent("onCollectValues",function(b){return this._con_f_used[b]?typeof this._con_f_used[b]=="object"?this._con_f_used[b]:!1:!0});this.attachEvent("onDynXLS",function(){this.xmlFileUrl=e.call(this,this.xmlFileUrl);return!0});this.attachEvent("onBeforeSorting",function(a,d,g){if(d=="connector"){var f=this;this.clearAndLoad(b.call(this,
this.xmlFileUrl,a,g),function(){f.setSortImgState(!0,a,g)});return!1}return!0});this.attachEvent("onFilterStart",function(b,a){return this._con_f_used.length?(this.clearAndLoad(d.call(this,this.xmlFileUrl,b,a)),!1):!0});this.attachEvent("onXLE",function(){});this._init_point_connector&&this._init_point_connector()},dhtmlXGridObject.prototype._con_f_used=[],dhtmlXGridObject.prototype._in_header_connector_text_filter=function(a,e){this._con_f_used[e]||(this._con_f_used[e]=1);return this._in_header_text_filter(a,
e)},dhtmlXGridObject.prototype._in_header_connector_select_filter=function(a,e){this._con_f_used[e]||(this._con_f_used[e]=2);return this._in_header_select_filter(a,e)},dhtmlXGridObject.prototype.load_connector=dhtmlXGridObject.prototype.load,dhtmlXGridObject.prototype.load=function(a,e,b){if(!this._colls_loaded&&this.cellType){for(var d=[],c=0;c<this.cellType.length;c++)(this.cellType[c].indexOf("co")==0||this._con_f_used[c]==2)&&d.push(c);d.length&&(arguments[0]+=(arguments[0].indexOf("?")!=-1?"&":
"?")+"connector=true&dhx_colls="+d.join(","))}return this.load_connector.apply(this,arguments)},dhtmlXGridObject.prototype._parseHead_connector=dhtmlXGridObject.prototype._parseHead,dhtmlXGridObject.prototype._parseHead=function(a,e,b){this._parseHead_connector.apply(this,arguments);if(!this._colls_loaded){for(var d=this.xmlLoader.doXPath("./coll_options",arguments[0]),c=0;c<d.length;c++){var h=d[c].getAttribute("for"),g=[],f=null;this.cellType[h]=="combo"&&(f=this.getColumnCombo(h));this.cellType[h].indexOf("co")==
0&&(f=this.getCombo(h));for(var i=this.xmlLoader.doXPath("./item",d[c]),j=0;j<i.length;j++){var n=i[j].getAttribute("value");if(f){var k=i[j].getAttribute("label")||n;f.addOption?f.addOption([[n,k]]):f.put(n,k);g[g.length]=k}else g[g.length]=n}this._con_f_used[h*1]&&(this._con_f_used[h*1]=g)}this._colls_loaded=!0}};
if(window.dataProcessor)dataProcessor.prototype.init_original=dataProcessor.prototype.init,dataProcessor.prototype.init=function(a){this.init_original(a);a._dataprocessor=this;this.setTransactionMode("POST",!0);this.serverProcessor+=(this.serverProcessor.indexOf("?")!=-1?"&":"?")+"editing=true"};dhtmlxError.catchError("LoadXML",function(a,e,b){b[0].status!=0&&alert(b[0].responseText)});window.Scheduler={_seed:0};Scheduler.plugin=function(a){this._schedulerPlugins.push(a);a(window.scheduler)};
Scheduler._schedulerPlugins=[];
Scheduler.getSchedulerInstance=function(){var a={version:"3.5"};dhtmlxEventable(a);a.init=function(b,d,c){d=d||new Date;c=c||"week";a.date.init();this._obj=typeof b=="string"?document.getElementById(b):b;this._els=[];this._scroll=!0;this._quirks=_isIE&&document.compatMode=="BackCompat";this._quirks7=_isIE&&navigator.appVersion.indexOf("MSIE 8")==-1;this.get_elements();this.init_templates();this.set_actions();dhtmlxEvent(window,"resize",function(){window.clearTimeout(a._resize_timer);a._resize_timer=
window.setTimeout(function(){a.callEvent("onSchedulerResize",[])&&(a.update_view(),a.callEvent("onAfterSchedulerResize",[]))},100)});this.set_sizes();a.callEvent("onSchedulerReady",[]);this.setCurrentView(d,c)};a.xy={nav_height:22,min_event_height:40,scale_width:50,bar_height:20,scroll_width:18,scale_height:20,month_scale_height:20,menu_width:25,margin_top:0,margin_left:0,editor_width:140,lightbox_additional_height:50};a.keys={edit_save:13,edit_cancel:27};a.set_sizes=function(){var b=this._x=this._obj.clientWidth-
this.xy.margin_left,a=this._y=this._obj.clientHeight-this.xy.margin_top,c=this._table_view?0:this.xy.scale_width+this.xy.scroll_width,h=this._table_view?-1:this.xy.scale_width;this.set_xy(this._els.dhx_cal_navline[0],b,this.xy.nav_height,0,0);this.set_xy(this._els.dhx_cal_header[0],b-c,this.xy.scale_height,h,this.xy.nav_height+(this._quirks?-1:1));var g=this._els.dhx_cal_navline[0].offsetHeight;if(g>0)this.xy.nav_height=g;var f=this.xy.scale_height+this.xy.nav_height+(this._quirks?-2:0);this.set_xy(this._els.dhx_cal_data[0],
b,a-(f+2),0,f+2)};a.set_xy=function(b,a,c,h,g){b.style.width=Math.max(0,a)+"px";b.style.height=Math.max(0,c)+"px";if(arguments.length>3)b.style.left=h+"px",b.style.top=g+"px"};a.get_elements=function(){for(var b=this._obj.getElementsByTagName("DIV"),d=0;d<b.length;d++){var c=b[d].className;c&&(c=c.split(" ")[0]);this._els[c]||(this._els[c]=[]);this._els[c].push(b[d]);var h=a.locale.labels[b[d].getAttribute("name")||c];if(h)b[d].innerHTML=h}};a.set_actions=function(){for(var b in this._els)if(this._click[b])for(var d=
0;d<this._els[b].length;d++)this._els[b][d].onclick=a._click[b];this._obj.onselectstart=function(){return!1};this._obj.onmousemove=function(b){a._on_mouse_move(b||event)};this._obj.onmousedown=function(b){a._on_mouse_down(b||event)};this._obj.onmouseup=function(b){a._on_mouse_up(b||event)};this._obj.ondblclick=function(b){a._on_dbl_click(b||event)};this._obj.oncontextmenu=function(b){var d=b||event,g=d.target||d.srcElement,f=a.callEvent("onContextMenu",[a._locate_event(g),d]);return f}};a.select=
function(b){if(this._select_id!=b)this.editStop(!1),this.unselect(),this._select_id=b,this.updateEvent(b)};a.unselect=function(b){if(!(b&&b!=this._select_id)){var a=this._select_id;this._select_id=null;a&&this.updateEvent(a)}};a.getState=function(){return{mode:this._mode,date:this._date,min_date:this._min_date,max_date:this._max_date,editor_id:this._edit_id,lightbox_id:this._lightbox_id,new_event:this._new_event,select_id:this._select_id,expanded:this.expanded,drag_id:this._drag_id,drag_mode:this._drag_mode}};
a._click={dhx_cal_data:function(b){var d=b?b.target:event.srcElement,c=a._locate_event(d),b=b||event;if(c){if(!a.callEvent("onClick",[c,b])||a.config.readonly)return}else a.callEvent("onEmptyClick",[a.getActionData(b).date,b]);if(c&&a.config.select){a.select(c);var h=d.className;if(h.indexOf("_icon")!=-1)a._click.buttons[h.split(" ")[1].replace("icon_","")](c)}else a._close_not_saved()},dhx_cal_prev_button:function(){a._click.dhx_cal_next_button(0,-1)},dhx_cal_next_button:function(b,d){a.setCurrentView(a.date.add(a.date[a._mode+
"_start"](a._date),d||1,a._mode))},dhx_cal_today_button:function(){a.setCurrentView(new Date)},dhx_cal_tab:function(){var b=this.getAttribute("name"),d=b.substring(0,b.search("_tab"));a.setCurrentView(a._date,d)},buttons:{"delete":function(b){var d=a.locale.labels.confirm_deleting;a._dhtmlx_confirm(d,a.locale.labels.title_confirm_deleting,function(){a.deleteEvent(b)})},edit:function(b){a.edit(b)},save:function(){a.editStop(!0)},details:function(b){a.showLightbox(b)},cancel:function(){a.editStop(!1)}}};
a._dhtmlx_confirm=function(b,a,c){if(!b)return c();var h={text:b};if(a)h.title=a;if(c)h.callback=function(b){b&&c()};dhtmlx.confirm(h)};a.addEventNow=function(b,a,c){var h={};b&&b.constructor.toString().match(/object/i)!==null&&(h=b,b=null);var g=(this.config.event_duration||this.config.time_step)*6E4;b||(b=Math.round((new Date).valueOf()/g)*g);var f=new Date(b);if(!a){var e=this.config.first_hour;e>f.getHours()&&(f.setHours(e),b=f.valueOf());a=b.valueOf()+g}var j=new Date(a);f.valueOf()==j.valueOf()&&
j.setTime(j.valueOf()+g);h.start_date=h.start_date||f;h.end_date=h.end_date||j;h.text=h.text||this.locale.labels.new_event;h.id=this._drag_id=this.uid();this._drag_mode="new-size";this._loading=!0;this.addEvent(h);this.callEvent("onEventCreated",[this._drag_id,c]);this._loading=!1;this._drag_event={};this._on_mouse_up(c)};a._on_dbl_click=function(b,d){d=d||b.target||b.srcElement;if(!this.config.readonly){var c=d.className.split(" ")[0];switch(c){case "dhx_scale_holder":case "dhx_scale_holder_now":case "dhx_month_body":case "dhx_wa_day_data":case "dhx_marked_timespan":if(!a.config.dblclick_create)break;
this.addEventNow(this.getActionData(b).date,null,b);break;case "dhx_cal_event":case "dhx_wa_ev_body":case "dhx_agenda_line":case "dhx_grid_event":case "dhx_cal_event_line":case "dhx_cal_event_clear":var h=this._locate_event(d);if(!this.callEvent("onDblClick",[h,b]))break;this.config.details_on_dblclick||this._table_view||!this.getEvent(h)._timed||!this.config.select?this.showLightbox(h):this.edit(h);break;case "dhx_time_block":case "dhx_cal_container":break;default:var g=this["dblclick_"+c];if(g)g.call(this,
b);else if(d.parentNode&&d!=this)return a._on_dbl_click(b,d.parentNode)}}};a._mouse_coords=function(b){var d,c=document.body,h=document.documentElement;d=b.pageX||b.pageY?{x:b.pageX,y:b.pageY}:{x:b.clientX+(c.scrollLeft||h.scrollLeft||0)-c.clientLeft,y:b.clientY+(c.scrollTop||h.scrollTop||0)-c.clientTop};d.x-=getAbsoluteLeft(this._obj)+(this._table_view?0:this.xy.scale_width);d.y-=getAbsoluteTop(this._obj)+this.xy.nav_height+(this._dy_shift||0)+this.xy.scale_height-this._els.dhx_cal_data[0].scrollTop;
d.ev=b;var g=this["mouse_"+this._mode];if(g)return g.call(this,d);if(this._table_view){if(!this._cols||!this._colsS)return d;for(var f=0,f=1;f<this._colsS.heights.length;f++)if(this._colsS.heights[f]>d.y)break;d.y=Math.ceil((Math.max(0,d.x/this._cols[0])+Math.max(0,f-1)*7)*1440/this.config.time_step);if(a._drag_mode||this._mode=="month")d.y=(Math.max(0,Math.ceil(d.x/this._cols[0])-1)+Math.max(0,f-1)*7)*1440/this.config.time_step;d.x=0}else d.x=Math.min(this._cols.length-1,Math.max(0,Math.ceil(d.x/
this._cols[0])-1)),d.y=Math.max(0,Math.ceil(d.y*60/(this.config.time_step*this.config.hour_size_px))-1)+this.config.first_hour*(60/this.config.time_step);return d};a._close_not_saved=function(){if((new Date).valueOf()-(a._new_event||0)>500&&a._edit_id){var b=a.locale.labels.confirm_closing;a._dhtmlx_confirm(b,a.locale.labels.title_confirm_closing,function(){a.editStop(a.config.positive_closing)})}};a._correct_shift=function(b,d){return b-=((new Date(a._min_date)).getTimezoneOffset()-(new Date(b)).getTimezoneOffset())*
6E4*(d?-1:1)};a._on_mouse_move=function(b){if(this._drag_mode){var d=this._mouse_coords(b);if(!this._drag_pos||d.custom||this._drag_pos.x!=d.x||this._drag_pos.y!=d.y){var c,h;this._edit_id!=this._drag_id&&this._close_not_saved();this._drag_pos=d;if(this._drag_mode=="create"){this._close_not_saved();this._loading=!0;c=this._get_date_from_pos(d).valueOf();var g=this.callEvent("onBeforeEventCreated",[b]);if(!g)return;if(!this._drag_start){this._drag_start=c;return}h=c;if(h==this._drag_start)return;this._drag_id=
this.uid();this.addEvent(new Date(this._drag_start),new Date(h),this.locale.labels.new_event,this._drag_id,d.fields);this.callEvent("onEventCreated",[this._drag_id,b]);this._loading=!1;this._drag_mode="new-size"}var f=this.getEvent(this._drag_id);if(this._drag_mode=="move")c=this._min_date.valueOf()+(d.y*this.config.time_step+d.x*1440)*6E4,!d.custom&&this._table_view&&(c+=this.date.time_part(f.start_date)*1E3),c=this._correct_shift(c),h=f.end_date.valueOf()-(f.start_date.valueOf()-c);else{c=f.start_date.valueOf();
h=f.end_date.valueOf();if(this._table_view){var e=this._min_date.valueOf()+d.y*this.config.time_step*6E4+(d.custom?0:864E5);this._mode=="month"&&(e=this._correct_shift(e,!1));d.resize_from_start?c=e:h=e}else if(h=this.date.date_part(new Date(f.end_date)).valueOf()+d.y*this.config.time_step*6E4,this._els.dhx_cal_data[0].style.cursor="s-resize",this._mode=="week"||this._mode=="day")h=this._correct_shift(h);if(this._drag_mode=="new-size")if(h<=this._drag_start){var j=d.shift||(this._table_view&&!d.custom?
864E5:0);c=h-(d.shift?0:j);h=this._drag_start+(j||this.config.time_step*6E4)}else c=this._drag_start;else h<=c&&(h=c+this.config.time_step*6E4)}var n=new Date(h-1),k=new Date(c);if(this._table_view||n.getDate()==k.getDate()&&n.getHours()<this.config.last_hour||a._allow_dnd)if(f.start_date=k,f.end_date=new Date(h),this.config.update_render){var m=a._els.dhx_cal_data[0].scrollTop;this.update_view();a._els.dhx_cal_data[0].scrollTop=m}else this.updateEvent(this._drag_id);this._table_view&&this.for_rendered(this._drag_id,
function(b){b.className+=" dhx_in_move"})}}else if(a.checkEvent("onMouseMove")){var l=this._locate_event(b.target||b.srcElement);this.callEvent("onMouseMove",[l,b])}};a._on_mouse_down=function(b,d){if(!this.config.readonly&&!this._drag_mode){var d=d||b.target||b.srcElement,c=d.className&&d.className.split(" ")[0];switch(c){case "dhx_cal_event_line":case "dhx_cal_event_clear":if(this._table_view)this._drag_mode="move";break;case "dhx_event_move":case "dhx_wa_ev_body":this._drag_mode="move";break;case "dhx_event_resize":this._drag_mode=
"resize";break;case "dhx_scale_holder":case "dhx_scale_holder_now":case "dhx_month_body":case "dhx_matrix_cell":case "dhx_marked_timespan":this._drag_mode="create";this.unselect(this._select_id);break;case "":if(d.parentNode)return a._on_mouse_down(b,d.parentNode);default:if(a.checkEvent("onMouseDown")&&a.callEvent("onMouseDown",[c])&&d.parentNode&&d!=this)return a._on_mouse_down(b,d.parentNode);this._drag_id=this._drag_mode=null}if(this._drag_mode){var h=this._locate_event(d);!this.config["drag_"+
this._drag_mode]||!this.callEvent("onBeforeDrag",[h,this._drag_mode,b])?this._drag_mode=this._drag_id=0:(this._drag_id=h,this._drag_event=a._lame_clone(this.getEvent(this._drag_id)||{}))}this._drag_start=null}};a._on_mouse_up=function(b){if(this._drag_mode&&this._drag_id){this._els.dhx_cal_data[0].style.cursor="default";var d=this.getEvent(this._drag_id);if(this._drag_event._dhx_changed||!this._drag_event.start_date||d.start_date.valueOf()!=this._drag_event.start_date.valueOf()||d.end_date.valueOf()!=
this._drag_event.end_date.valueOf()){var c=this._drag_mode=="new-size";if(this.callEvent("onBeforeEventChanged",[d,b,c,this._drag_event])){var h=this._drag_id;this._drag_id=this._drag_mode=null;if(c&&this.config.edit_on_create){this.unselect();this._new_event=new Date;if(this._table_view||this.config.details_on_create||!this.config.select)return this.showLightbox(h);this._drag_pos=!0;this._select_id=this._edit_id=h}else this._new_event||this.callEvent(c?"onEventAdded":"onEventChanged",[h,this.getEvent(h)])}else c?
this.deleteEvent(d.id,!0):(this._drag_event._dhx_changed=!1,a._lame_copy(d,this._drag_event),this.updateEvent(d.id))}this._drag_pos&&this.render_view_data()}this._drag_pos=this._drag_mode=this._drag_id=null};a.update_view=function(){this._reset_scale();if(this._load_mode&&this._load())return this._render_wait=!0;this.render_view_data()};a.updateView=function(b,a){var b=b||this._date,a=a||this._mode,c="dhx_cal_data";this._mode?this._obj.className=this._obj.className.replace("dhx_scheduler_"+this._mode,
"dhx_scheduler_"+a):this._obj.className+=" dhx_scheduler_"+a;var h=this._mode==a&&this.config.preserve_scroll?this._els[c][0].scrollTop:!1;if(this[this._mode+"_view"]&&a&&this._mode!=a)this[this._mode+"_view"](!1);this._close_not_saved();var g="dhx_multi_day";this._els[g]&&(this._els[g][0].parentNode.removeChild(this._els[g][0]),this._els[g]=null);this._mode=a;this._date=b;this._table_view=this._mode=="month";for(var f=this._els.dhx_cal_tab,e=0;e<f.length;e++){var j=f[e].className,j=j.replace(/ active/g,
"");f[e].getAttribute("name")==this._mode+"_tab"&&(j+=" active");f[e].className=j}var n=this[this._mode+"_view"];n?n(!0):this.update_view();if(typeof h=="number")this._els[c][0].scrollTop=h};a.setCurrentView=function(b,a){this.callEvent("onBeforeViewChange",[this._mode,this._date,a,b])&&(this.updateView(b,a),this.callEvent("onViewChange",[this._mode,this._date]))};a._render_x_header=function(b,a,c,h){var g=document.createElement("DIV");g.className="dhx_scale_bar";this.set_xy(g,this._cols[b]-1,this.xy.scale_height-
2,a,0);g.innerHTML=this.templates[this._mode+"_scale_date"](c,this._mode);h.appendChild(g)};a._reset_scale=function(){if(this.templates[this._mode+"_date"]){var b=this._els.dhx_cal_header[0],d=this._els.dhx_cal_data[0],c=this.config;b.innerHTML="";d.scrollTop=0;d.innerHTML="";var h=(c.readonly||!c.drag_resize?" dhx_resize_denied":"")+(c.readonly||!c.drag_move?" dhx_move_denied":"");if(h)d.className="dhx_cal_data"+h;this._scales={};this._cols=[];this._colsS={height:0};this._dy_shift=0;this.set_sizes();
var g=parseInt(b.style.width,10),e=0,i,j,n,k;j=this.date[this._mode+"_start"](new Date(this._date.valueOf()));i=n=this._table_view?a.date.week_start(j):j;k=this.date.date_part(new Date);var m=a.date.add(j,1,this._mode),l=7;if(!this._table_view){var s=this.date["get_"+this._mode+"_end"];s&&(m=s(j));l=Math.round((m.valueOf()-j.valueOf())/864E5)}this._min_date=i;this._els.dhx_cal_date[0].innerHTML=this.templates[this._mode+"_date"](j,m,this._mode);for(var p=0;p<l;p++){this._cols[p]=Math.floor(g/(l-p));
this._render_x_header(p,e,i,b);if(!this._table_view){var o=document.createElement("DIV"),t="dhx_scale_holder";i.valueOf()==k.valueOf()&&(t="dhx_scale_holder_now");o.className=t+" "+this.templates.week_date_class(i,k);this.set_xy(o,this._cols[p]-1,c.hour_size_px*(c.last_hour-c.first_hour),e+this.xy.scale_width+1,0);d.appendChild(o);this.callEvent("onScaleAdd",[o,i])}i=this.date.add(i,1,"day");g-=this._cols[p];e+=this._cols[p];this._colsS[p]=(this._cols[p-1]||0)+(this._colsS[p-1]||(this._table_view?
0:this.xy.scale_width+2));this._colsS.col_length=l+1}this._max_date=i;this._colsS[l]=this._cols[l-1]+this._colsS[l-1];if(this._table_view)this._reset_month_scale(d,j,n);else if(this._reset_hours_scale(d,j,n),c.multi_day){var q="dhx_multi_day";this._els[q]&&(this._els[q][0].parentNode.removeChild(this._els[q][0]),this._els[q]=null);var r=this._els.dhx_cal_navline[0],u=r.offsetHeight+this._els.dhx_cal_header[0].offsetHeight+1,v=document.createElement("DIV");v.className=q;v.style.visibility="hidden";
this.set_xy(v,this._colsS[this._colsS.col_length-1]+this.xy.scroll_width,0,0,u);d.parentNode.insertBefore(v,d);var w=v.cloneNode(!0);w.className=q+"_icon";w.style.visibility="hidden";this.set_xy(w,this.xy.scale_width,0,0,u);v.appendChild(w);this._els[q]=[v,w];this._els[q][0].onclick=this._click.dhx_cal_data}}};a._reset_hours_scale=function(b){var d=document.createElement("DIV");d.className="dhx_scale_holder";for(var c=new Date(1980,1,1,this.config.first_hour,0,0),h=this.config.first_hour*1;h<this.config.last_hour;h++){var g=
document.createElement("DIV");g.className="dhx_scale_hour";g.style.height=this.config.hour_size_px-(this._quirks?0:1)+"px";g.style.width=this.xy.scale_width+"px";g.innerHTML=a.templates.hour_scale(c);d.appendChild(g);c=this.date.add(c,1,"hour")}b.appendChild(d);if(this.config.scroll_hour)b.scrollTop=this.config.hour_size_px*(this.config.scroll_hour-this.config.first_hour)};a._reset_month_scale=function(b,d,c){var h=a.date.add(d,1,"month"),g=new Date;this.date.date_part(g);this.date.date_part(c);var e=
Math.ceil(Math.round((h.valueOf()-c.valueOf())/864E5)/7),i=[],j=Math.floor(b.clientHeight/e)-22;this._colsS.height=j+22;for(var n=this._colsS.heights=[],k=0;k<=7;k++)i[k]=" style='height:"+j+"px; width:"+((this._cols[k]||0)-1)+"px;' ";var m=0;this._min_date=c;for(var l="<table cellpadding='0' cellspacing='0'>",s=[],k=0;k<e;k++){l+="<tr>";for(var p=0;p<7;p++){l+="<td";var o="";c<d?o="dhx_before":c>=h?o="dhx_after":c.valueOf()==g.valueOf()&&(o="dhx_now");l+=" class='"+o+" "+this.templates.month_date_class(c,
g)+"' ";l+="><div class='dhx_month_head'>"+this.templates.month_day(c)+"</div><div class='dhx_month_body' "+i[p]+"></div></td>";s.push(c);c=this.date.add(c,1,"day")}l+="</tr>";n[k]=m;m+=this._colsS.height}l+="</table>";this._max_date=c;b.innerHTML=l;this._scales={};for(var t=b.getElementsByTagName("div"),k=0;k<s.length;k++){var q=t[k*2+1],r=s[k];this._scales[+r]=q}for(k=0;k<s.length;k++)r=s[k],this.callEvent("onScaleAdd",[this._scales[+r],r]);return c};a.getLabel=function(b,a){for(var c=this.config.lightbox.sections,
h=0;h<c.length;h++)if(c[h].map_to==b)for(var g=c[h].options,e=0;e<g.length;e++)if(g[e].key==a)return g[e].label;return""};a.updateCollection=function(b,d){var c=a.serverList(b);if(!c)return!1;c.splice(0,c.length);c.push.apply(c,d||[]);a.callEvent("onOptionsLoad",[]);a.resetLightbox();return!0};a._lame_clone=function(b,d){var c,h,e,d=d||[];for(c=0;c<d.length;c+=2)if(b===d[c])return d[c+1];if(b&&typeof b=="object"){e={};h=[Array,Date,Number,String,Boolean];for(c=0;c<h.length;c++)b instanceof h[c]&&
(e=c?new h[c](b):new h[c]);d.push(b,e);for(c in b)Object.prototype.hasOwnProperty.apply(b,[c])&&(e[c]=a._lame_clone(b[c],d))}return e||b};a._lame_copy=function(b,a){for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c]);return b};a._get_date_from_pos=function(b){var a=this._min_date.valueOf()+(b.y*this.config.time_step+(this._table_view?0:b.x)*1440)*6E4;return new Date(this._correct_shift(a))};a.getActionData=function(b){var a=this._mouse_coords(b);return{date:this._get_date_from_pos(a),section:a.section}};
a.date={init:function(){for(var b=a.locale.date.month_short,d=a.locale.date.month_short_hash={},c=0;c<b.length;c++)d[b[c]]=c;b=a.locale.date.month_full;d=a.locale.date.month_full_hash={};for(c=0;c<b.length;c++)d[b[c]]=c},date_part:function(b){b.setHours(0);b.setMinutes(0);b.setSeconds(0);b.setMilliseconds(0);b.getHours()!=0&&b.setTime(b.getTime()+36E5*(24-b.getHours()));return b},time_part:function(b){return(b.valueOf()/1E3-b.getTimezoneOffset()*60)%86400},week_start:function(b){var d=b.getDay();
a.config.start_on_monday&&(d===0?d=6:d--);return this.date_part(this.add(b,-1*d,"day"))},month_start:function(b){b.setDate(1);return this.date_part(b)},year_start:function(b){b.setMonth(0);return this.month_start(b)},day_start:function(b){return this.date_part(b)},add:function(b,d,c){var h=new Date(b.valueOf());switch(c){case "week":d*=7;case "day":h.setDate(h.getDate()+d);!b.getHours()&&h.getHours()&&h.setTime(h.getTime()+36E5*(24-h.getHours()));break;case "month":var e=h.getMonth()+d,f=new Date(h);
h.setMonth(e);h.getMonth()!=e&&h.getMonth()!=e%12&&(f.setDate(1),f.setMonth(e),f.setDate((new Date(f.getFullYear(),e+1,0)).getDate()),h=f);break;case "year":h.setYear(h.getFullYear()+d);break;case "hour":h.setHours(h.getHours()+d);break;case "minute":h.setMinutes(h.getMinutes()+d);break;default:return a.date["add_"+c](b,d,c)}return h},to_fixed:function(b){return b<10?"0"+b:b},copy:function(b){return new Date(b.valueOf())},date_to_str:function(b,a){b=b.replace(/%[a-zA-Z]/g,function(b){switch(b){case "%d":return'"+scheduler.date.to_fixed(date.getDate())+"';
case "%m":return'"+scheduler.date.to_fixed((date.getMonth()+1))+"';case "%j":return'"+date.getDate()+"';case "%n":return'"+(date.getMonth()+1)+"';case "%y":return'"+scheduler.date.to_fixed(date.getFullYear()%100)+"';case "%Y":return'"+date.getFullYear()+"';case "%D":return'"+scheduler.locale.date.day_short[date.getDay()]+"';case "%l":return'"+scheduler.locale.date.day_full[date.getDay()]+"';case "%M":return'"+scheduler.locale.date.month_short[date.getMonth()]+"';case "%F":return'"+scheduler.locale.date.month_full[date.getMonth()]+"';
case "%h":return'"+scheduler.date.to_fixed((date.getHours()+11)%12+1)+"';case "%g":return'"+((date.getHours()+11)%12+1)+"';case "%G":return'"+date.getHours()+"';case "%H":return'"+scheduler.date.to_fixed(date.getHours())+"';case "%i":return'"+scheduler.date.to_fixed(date.getMinutes())+"';case "%a":return'"+(date.getHours()>11?"pm":"am")+"';case "%A":return'"+(date.getHours()>11?"PM":"AM")+"';case "%s":return'"+scheduler.date.to_fixed(date.getSeconds())+"';case "%W":return'"+scheduler.date.to_fixed(scheduler.date.getISOWeek(date))+"';
default:return b}});a&&(b=b.replace(/date\.get/g,"date.getUTC"));return new Function("date",'return "'+b+'";')},str_to_date:function(b,a){for(var c="var temp=date.match(/[a-zA-Z]+|[0-9]+/g);",h=b.match(/%[a-zA-Z]/g),e=0;e<h.length;e++)switch(h[e]){case "%j":case "%d":c+="set[2]=temp["+e+"]||1;";break;case "%n":case "%m":c+="set[1]=(temp["+e+"]||1)-1;";break;case "%y":c+="set[0]=temp["+e+"]*1+(temp["+e+"]>50?1900:2000);";break;case "%g":case "%G":case "%h":case "%H":c+="set[3]=temp["+e+"]||0;";break;
case "%i":c+="set[4]=temp["+e+"]||0;";break;case "%Y":c+="set[0]=temp["+e+"]||0;";break;case "%a":case "%A":c+="set[3]=set[3]%12+((temp["+e+"]||'').toLowerCase()=='am'?0:12);";break;case "%s":c+="set[5]=temp["+e+"]||0;";break;case "%M":c+="set[1]=scheduler.locale.date.month_short_hash[temp["+e+"]]||0;";break;case "%F":c+="set[1]=scheduler.locale.date.month_full_hash[temp["+e+"]]||0;"}var f="set[0],set[1],set[2],set[3],set[4],set[5]";a&&(f=" Date.UTC("+f+")");return new Function("date","var set=[0,0,1,0,0,0]; "+
c+" return new Date("+f+");")},getISOWeek:function(b){if(!b)return!1;var a=b.getDay();a===0&&(a=7);var c=new Date(b.valueOf());c.setDate(b.getDate()+(4-a));var e=c.getFullYear(),g=Math.round((c.getTime()-(new Date(e,0,1)).getTime())/864E5),f=1+Math.floor(g/7);return f},getUTCISOWeek:function(b){return this.getISOWeek(b)},convert_to_utc:function(b){return new Date(b.getUTCFullYear(),b.getUTCMonth(),b.getUTCDate(),b.getUTCHours(),b.getUTCMinutes(),b.getUTCSeconds())}};a.locale={date:{month_full:"January,February,March,April,May,June,July,August,September,October,November,December".split(","),
month_short:"Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec".split(","),day_full:"Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday".split(","),day_short:"Sun,Mon,Tue,Wed,Thu,Fri,Sat".split(",")},labels:{dhx_cal_today_button:"Today",day_tab:"Day",week_tab:"Week",month_tab:"Month",new_event:"New event",icon_save:"Save",icon_cancel:"Cancel",icon_details:"Details",icon_edit:"Edit",icon_delete:"Delete",confirm_closing:"",confirm_deleting:"Event will be deleted permanently, are you sure?",section_description:"Description",
section_time:"Time period",full_day:"Full day",confirm_recurring:"Do you want to edit the whole set of repeated events?",section_recurring:"Repeat event",button_recurring:"Disabled",button_recurring_open:"Enabled",button_edit_series:"Edit series",button_edit_occurrence:"Edit occurrence",agenda_tab:"Agenda",date:"Date",description:"Description",year_tab:"Year",week_agenda_tab:"Agenda",grid_tab:"Grid"}};a.config={default_date:"%j %M %Y",month_date:"%F %Y",load_date:"%Y-%m-%d",week_date:"%l",day_date:"%D, %F %j",
hour_date:"%H:%i",month_day:"%d",xml_date:"%m/%d/%Y %H:%i",api_date:"%d-%m-%Y %H:%i",hour_size_px:42,time_step:5,start_on_monday:1,first_hour:0,last_hour:24,readonly:!1,drag_resize:1,drag_move:1,drag_create:1,dblclick_create:1,edit_on_create:1,details_on_create:0,click_form_details:0,cascade_event_display:!1,cascade_event_count:4,cascade_event_margin:30,drag_lightbox:!0,preserve_scroll:!0,select:!0,server_utc:!1,positive_closing:!1,icons_edit:["icon_save","icon_cancel"],icons_select:["icon_details",
"icon_edit","icon_delete"],buttons_left:["dhx_save_btn","dhx_cancel_btn"],buttons_right:["dhx_delete_btn"],lightbox:{sections:[{name:"description",height:200,map_to:"text",type:"textarea",focus:!0},{name:"time",height:72,type:"time",map_to:"auto"}]},highlight_displayed_event:!0,displayed_event_color:"#ffc5ab",displayed_event_text_color:"#7e2727"};a.templates={};a.init_templates=function(){var b=a.locale.labels;b.dhx_save_btn=b.icon_save;b.dhx_cancel_btn=b.icon_cancel;b.dhx_delete_btn=b.icon_delete;
var d=a.date.date_to_str,c=a.config,e=function(b,a){for(var d in a)b[d]||(b[d]=a[d])};e(a.templates,{day_date:d(c.default_date),month_date:d(c.month_date),week_date:function(b,d){return a.templates.day_date(b)+" &ndash; "+a.templates.day_date(a.date.add(d,-1,"day"))},day_scale_date:d(c.default_date),month_scale_date:d(c.week_date),week_scale_date:d(c.day_date),hour_scale:d(c.hour_date),time_picker:d(c.hour_date),event_date:d(c.hour_date),month_day:d(c.month_day),xml_date:a.date.str_to_date(c.xml_date,
c.server_utc),load_format:d(c.load_date,c.server_utc),xml_format:d(c.xml_date,c.server_utc),api_date:a.date.str_to_date(c.api_date),event_header:function(b,d){return a.templates.event_date(b)+" - "+a.templates.event_date(d)},event_text:function(b,a,d){return d.text},event_class:function(){return""},month_date_class:function(){return""},week_date_class:function(){return""},event_bar_date:function(b){return a.templates.event_date(b)+" "},event_bar_text:function(b,a,d){return d.text}});this.callEvent("onTemplatesReady",
[])};a.uid=function(){if(!this._seed)this._seed=(new Date).valueOf();return this._seed++};a._events={};a.clearAll=function(){this._events={};this._loaded={};this.clear_view()};a.addEvent=function(b,d,c,e,g){if(!arguments.length)return this.addEventNow();var f=b;if(arguments.length!=1)f=g||{},f.start_date=b,f.end_date=d,f.text=c,f.id=e;f.id=f.id||a.uid();f.text=f.text||"";if(typeof f.start_date=="string")f.start_date=this.templates.api_date(f.start_date);if(typeof f.end_date=="string")f.end_date=this.templates.api_date(f.end_date);
var i=(this.config.event_duration||this.config.time_step)*6E4;f.start_date.valueOf()==f.end_date.valueOf()&&f.end_date.setTime(f.end_date.valueOf()+i);f._timed=this.is_one_day_event(f);var j=!this._events[f.id];this._events[f.id]=f;this.event_updated(f);this._loading||this.callEvent(j?"onEventAdded":"onEventChanged",[f.id,f]);return f.id};a.deleteEvent=function(b,a){var c=this._events[b];if(a||this.callEvent("onBeforeEventDelete",[b,c])&&this.callEvent("onConfirmedBeforeEventDelete",[b,c]))c&&(delete this._events[b],
this.unselect(b),this.event_updated(c)),this.callEvent("onEventDeleted",[b,c])};a.getEvent=function(b){return this._events[b]};a.setEvent=function(b,a){this._events[b]=a};a.for_rendered=function(b,a){for(var c=this._rendered.length-1;c>=0;c--)this._rendered[c].getAttribute("event_id")==b&&a(this._rendered[c],c)};a.changeEventId=function(b,a){if(b!=a){var c=this._events[b];if(c)c.id=a,this._events[a]=c,delete this._events[b];this.for_rendered(b,function(b){b.setAttribute("event_id",a)});if(this._select_id==
b)this._select_id=a;if(this._edit_id==b)this._edit_id=a;this.callEvent("onEventIdChange",[b,a])}};(function(){for(var b="text,Text,start_date,StartDate,end_date,EndDate".split(","),d=function(b){return function(d){return a.getEvent(d)[b]}},c=function(b){return function(d,c){var e=a.getEvent(d);e[b]=c;e._changed=!0;e._timed=this.is_one_day_event(e);a.event_updated(e,!0)}},e=0;e<b.length;e+=2)a["getEvent"+b[e+1]]=d(b[e]),a["setEvent"+b[e+1]]=c(b[e])})();a.event_updated=function(b){this.is_visible_events(b)?
this.render_view_data():this.clear_event(b.id)};a.is_visible_events=function(b){return b.start_date<this._max_date&&this._min_date<b.end_date};a.is_one_day_event=function(b){var a=b.end_date.getDate()-b.start_date.getDate();return a?(a<0&&(a=Math.ceil((b.end_date.valueOf()-b.start_date.valueOf())/864E5)),a==1&&!b.end_date.getHours()&&!b.end_date.getMinutes()&&(b.start_date.getHours()||b.start_date.getMinutes())):b.start_date.getMonth()==b.end_date.getMonth()&&b.start_date.getFullYear()==b.end_date.getFullYear()};
a.get_visible_events=function(b){var a=[],c;for(c in this._events)this.is_visible_events(this._events[c])&&(!b||this._events[c]._timed)&&this.filter_event(c,this._events[c])&&a.push(this._events[c]);return a};a.filter_event=function(b,a){var c=this["filter_"+this._mode];return c?c(b,a):!0};a.render_view_data=function(b,a){if(!b){if(this._not_render){this._render_wait=!0;return}this._render_wait=!1;this.clear_view();b=this.get_visible_events(!(this._table_view||this.config.multi_day))}if(this.config.multi_day&&
!this._table_view){for(var c=[],e=[],g=0;g<b.length;g++)b[g]._timed?c.push(b[g]):e.push(b[g]);this._rendered_location=this._els.dhx_multi_day[0];this._table_view=!0;this.render_data(e,a);this._table_view=!1;this._rendered_location=this._els.dhx_cal_data[0];this._table_view=!1;this.render_data(c,a)}else this._rendered_location=this._els.dhx_cal_data[0],this.render_data(b,a)};a.render_data=function(b,a){for(var b=this._pre_render_events(b,a),c=0;c<b.length;c++)this._table_view?this.render_event_bar(b[c]):
this.render_event(b[c])};a._pre_render_events=function(b,d){var c=this.xy.bar_height,e=this._colsS.heights,g=this._colsS.heights=[0,0,0,0,0,0,0],f=this._els.dhx_cal_data[0],b=this._table_view?this._pre_render_events_table(b,d):this._pre_render_events_line(b,d);if(this._table_view)if(d)this._colsS.heights=e;else{var i=f.firstChild;if(i.rows){for(var j=0;j<i.rows.length;j++){g[j]++;if(g[j]*c>this._colsS.height-22){for(var n=i.rows[j].cells,k=0;k<n.length;k++)n[k].childNodes[1].style.height=g[j]*c+"px";
g[j]=(g[j-1]||0)+n[0].offsetHeight}g[j]=(g[j-1]||0)+i.rows[j].cells[0].offsetHeight}g.unshift(0);if(i.parentNode.offsetHeight<i.parentNode.scrollHeight&&!i._h_fix){for(j=0;j<i.rows.length;j++){var m=i.rows[j].cells[6].childNodes[0],l=m.offsetWidth-a.xy.scroll_width+"px";m.style.width=l;m.nextSibling.style.width=l}i._h_fix=!0}}else if(!b.length&&this._els.dhx_multi_day[0].style.visibility=="visible"&&(g[0]=-1),b.length||g[0]==-1){var s=i.parentNode.childNodes,p=(g[0]+1)*c+1+"px";f.style.top=this._els.dhx_cal_navline[0].offsetHeight+
this._els.dhx_cal_header[0].offsetHeight+parseInt(p,10)+"px";f.style.height=this._obj.offsetHeight-parseInt(f.style.top,10)-(this.xy.margin_top||0)+"px";var o=this._els.dhx_multi_day[0];o.style.height=p;o.style.visibility=g[0]==-1?"hidden":"visible";o=this._els.dhx_multi_day[1];o.style.height=p;o.style.visibility=g[0]==-1?"hidden":"visible";o.className=g[0]?"dhx_multi_day_icon":"dhx_multi_day_icon_small";this._dy_shift=(g[0]+1)*c;g[0]=0}}return b};a._get_event_sday=function(b){return Math.floor((b.start_date.valueOf()-
this._min_date.valueOf())/864E5)};a._get_event_mapped_end_date=function(b){var a=b.end_date;if(this.config.separate_short_events){var c=(b.end_date-b.start_date)/6E4;c<this._min_mapped_duration&&(a=this.date.add(a,this._min_mapped_duration-c,"minute"))}return a};a._pre_render_events_line=function(b,a){b.sort(function(b,a){return b.start_date.valueOf()==a.start_date.valueOf()?b.id>a.id?1:-1:b.start_date>a.start_date?1:-1});var c=[],e=[];this._min_mapped_duration=Math.ceil(this.xy.min_event_height*
60/this.config.hour_size_px);for(var g=0;g<b.length;g++){var f=b[g],i=f.start_date,j=f.end_date,n=i.getHours(),k=j.getHours();f._sday=this._get_event_sday(f);c[f._sday]||(c[f._sday]=[]);if(!a){f._inner=!1;for(var m=c[f._sday];m.length;){var l=m[m.length-1],s=this._get_event_mapped_end_date(l);if(s.valueOf()<=f.start_date.valueOf())m.splice(m.length-1,1);else break}for(var p=!1,o=0;o<m.length;o++)if(l=m[o],s=this._get_event_mapped_end_date(l),s.valueOf()<=f.start_date.valueOf()){p=!0;f._sorder=l._sorder;
m.splice(o,1);f._inner=!0;break}if(m.length)m[m.length-1]._inner=!0;if(!p)if(m.length)if(m.length<=m[m.length-1]._sorder){if(m[m.length-1]._sorder)for(o=0;o<m.length;o++){for(var t=!1,q=0;q<m.length;q++)if(m[q]._sorder==o){t=!0;break}if(!t){f._sorder=o;break}}else f._sorder=0;f._inner=!0}else{t=m[0]._sorder;for(o=1;o<m.length;o++)if(m[o]._sorder>t)t=m[o]._sorder;f._sorder=t+1;f._inner=!1}else f._sorder=0;m.push(f);m.length>(m.max_count||0)?(m.max_count=m.length,f._count=m.length):f._count=f._count?
f._count:1}if(n<this.config.first_hour||k>=this.config.last_hour)if(e.push(f),b[g]=f=this._copy_event(f),n<this.config.first_hour&&(f.start_date.setHours(this.config.first_hour),f.start_date.setMinutes(0)),k>=this.config.last_hour&&(f.end_date.setMinutes(0),f.end_date.setHours(this.config.last_hour)),f.start_date>f.end_date||n==this.config.last_hour)b.splice(g,1),g--}if(!a){for(g=0;g<b.length;g++)b[g]._count=c[b[g]._sday].max_count;for(g=0;g<e.length;g++)e[g]._count=c[e[g]._sday].max_count}return b};
a._time_order=function(b){b.sort(function(b,a){return b.start_date.valueOf()==a.start_date.valueOf()?b._timed&&!a._timed?1:!b._timed&&a._timed?-1:b.id>a.id?1:-1:b.start_date>a.start_date?1:-1})};a._pre_render_events_table=function(b,a){this._time_order(b);for(var c=[],e=[[],[],[],[],[],[],[]],g=this._colsS.heights,f,i=this._cols.length,j={},n=0;n<b.length;n++){var k=b[n],m=k.id;j[m]||(j[m]={first_chunk:!0,last_chunk:!0});var l=j[m],s=f||k.start_date,p=k.end_date;if(s<this._min_date)l.first_chunk=
!1,s=this._min_date;if(p>this._max_date)l.last_chunk=!1,p=this._max_date;var o=this.locate_holder_day(s,!1,k);k._sday=o%i;var t=this.locate_holder_day(p,!0,k)||i;k._eday=t%i||i;k._length=t-o;k._sweek=Math.floor((this._correct_shift(s.valueOf(),1)-this._min_date.valueOf())/(864E5*i));var q=e[k._sweek],r;for(r=0;r<q.length;r++)if(q[r]._eday<=k._sday)break;if(!k._sorder||!a)k._sorder=r;if(k._sday+k._length<=i)f=null,c.push(k),q[r]=k,g[k._sweek]=q.length-1,k._first_chunk=l.first_chunk,k._last_chunk=l.last_chunk;
else{var u=this._copy_event(k);u.id=k.id;u._length=i-k._sday;u._eday=i;u._sday=k._sday;u._sweek=k._sweek;u._sorder=k._sorder;u.end_date=this.date.add(s,u._length,"day");if(u._first_chunk=l.first_chunk)l.first_chunk=!1;c.push(u);q[r]=u;f=u.end_date;g[k._sweek]=q.length-1;n--}}return c};a._copy_dummy=function(){var b=new Date(this.start_date),a=new Date(this.end_date);this.start_date=b;this.end_date=a};a._copy_event=function(b){this._copy_dummy.prototype=b;return new this._copy_dummy};a._rendered=[];
a.clear_view=function(){for(var b=0;b<this._rendered.length;b++){var a=this._rendered[b];a.parentNode&&a.parentNode.removeChild(a)}this._rendered=[]};a.updateEvent=function(b){var a=this.getEvent(b);this.clear_event(b);if(a&&this.is_visible_events(a)&&this.filter_event(b,a)&&(this._table_view||this.config.multi_day||a._timed))this.config.update_render?this.render_view_data():this.render_view_data([a],!0)};a.clear_event=function(b){this.for_rendered(b,function(b,c){b.parentNode&&b.parentNode.removeChild(b);
a._rendered.splice(c,1)})};a.render_event=function(b){var d=a.xy.menu_width;if(!(b._sday<0)){var c=a.locate_holder(b._sday);if(c){var e=b.start_date.getHours()*60+b.start_date.getMinutes(),g=b.end_date.getHours()*60+b.end_date.getMinutes()||a.config.last_hour*60,f=b._count||1,i=b._sorder||0,j=Math.round((e*6E4-this.config.first_hour*36E5)*this.config.hour_size_px/36E5)%(this.config.hour_size_px*24),n=Math.max(a.xy.min_event_height,(g-e)*this.config.hour_size_px/60),k=Math.floor((c.clientWidth-d)/
f),m=i*k+1;b._inner||(k*=f-i);if(this.config.cascade_event_display)var l=this.config.cascade_event_count,s=this.config.cascade_event_margin,m=i%l*s,p=b._inner?(f-i-1)%l*s/2:0,k=Math.floor(c.clientWidth-d-m-p);var o=this._render_v_bar(b.id,d+m,j,k,n,b._text_style,a.templates.event_header(b.start_date,b.end_date,b),a.templates.event_text(b.start_date,b.end_date,b));this._rendered.push(o);c.appendChild(o);m=m+parseInt(c.style.left,10)+d;if(this._edit_id==b.id){o.style.zIndex=1;k=Math.max(k-4,a.xy.editor_width);
o=document.createElement("DIV");o.setAttribute("event_id",b.id);this.set_xy(o,k,n-20,m,j+14);o.className="dhx_cal_editor";var t=document.createElement("DIV");this.set_xy(t,k-6,n-26);t.style.cssText+=";margin:2px 2px 2px 2px;overflow:hidden;";o.appendChild(t);this._els.dhx_cal_data[0].appendChild(o);this._rendered.push(o);t.innerHTML="<textarea class='dhx_cal_editor'>"+b.text+"</textarea>";if(this._quirks7)t.firstChild.style.height=n-12+"px";this._editor=t.firstChild;this._editor.onkeydown=function(b){if((b||
event).shiftKey)return!0;var d=(b||event).keyCode;d==a.keys.edit_save&&a.editStop(!0);d==a.keys.edit_cancel&&a.editStop(!1)};this._editor.onselectstart=function(b){return(b||event).cancelBubble=!0};t.firstChild.focus();this._els.dhx_cal_data[0].scrollLeft=0;t.firstChild.select()}if(this.xy.menu_width!==0&&this._select_id==b.id){if(this.config.cascade_event_display&&this._drag_mode)o.style.zIndex=1;for(var q=this.config["icons_"+(this._edit_id==b.id?"edit":"select")],r="",u=b.color?"background-color: "+
b.color+";":"",v=b.textColor?"color: "+b.textColor+";":"",w=0;w<q.length;w++)r+="<div class='dhx_menu_icon "+q[w]+"' style='"+u+""+v+"' title='"+this.locale.labels[q[w]]+"'></div>";var y=this._render_v_bar(b.id,m-d+1,j,d,q.length*20+26-2,"","<div style='"+u+""+v+"' class='dhx_menu_head'></div>",r,!0);y.style.left=m-d+1;this._els.dhx_cal_data[0].appendChild(y);this._rendered.push(y)}}}};a._render_v_bar=function(b,d,c,e,g,f,i,j,n){var k=document.createElement("DIV"),m=this.getEvent(b),l=n?"dhx_cal_event dhx_cal_select_menu":
"dhx_cal_event",s=a.templates.event_class(m.start_date,m.end_date,m);s&&(l=l+" "+s);var p=m.color?"background:"+m.color+";":"",o=m.textColor?"color:"+m.textColor+";":"",t='<div event_id="'+b+'" class="'+l+'" style="position:absolute; top:'+c+"px; left:"+d+"px; width:"+(e-4)+"px; height:"+g+"px;"+(f||"")+'"></div>';k.innerHTML=t;var q=k.cloneNode(!0).firstChild;if(!a.renderEvent||n||!a.renderEvent(q,m)){var q=k.firstChild,r='<div class="dhx_event_move dhx_header" style=" width:'+(e-6)+"px;"+p+'" >&nbsp;</div>';
r+='<div class="dhx_event_move dhx_title" style="'+p+""+o+'">'+i+"</div>";r+='<div class="dhx_body" style=" width:'+(e-(this._quirks?4:14))+"px; height:"+(g-(this._quirks?20:30)+1)+"px;"+p+""+o+'">'+j+"</div>";var u="dhx_event_resize dhx_footer";n&&(u="dhx_resize_denied "+u);r+='<div class="'+u+'" style=" width:'+(e-8)+"px;"+(n?" margin-top:-1px;":"")+""+p+""+o+'" ></div>';q.innerHTML=r}return q};a.locate_holder=function(b){return this._mode=="day"?this._els.dhx_cal_data[0].firstChild:this._els.dhx_cal_data[0].childNodes[b]};
a.locate_holder_day=function(b,a){var c=Math.floor((this._correct_shift(b,1)-this._min_date)/864E5);a&&this.date.time_part(b)&&c++;return c};a.render_event_bar=function(b){var d=this._rendered_location,c=this._colsS[b._sday],e=this._colsS[b._eday];e==c&&(e=this._colsS[b._eday+1]);var g=this.xy.bar_height,f=this._colsS.heights[b._sweek]+(this._colsS.height?this.xy.month_scale_height+2:2)+b._sorder*g,i=document.createElement("DIV"),j="dhx_cal_event_clear";b._timed||(j="dhx_cal_event_line",b.hasOwnProperty("_first_chunk")&&
b._first_chunk&&(j+=" dhx_cal_event_line_start"),b.hasOwnProperty("_last_chunk")&&b._last_chunk&&(j+=" dhx_cal_event_line_end"));var n=a.templates.event_class(b.start_date,b.end_date,b);n&&(j=j+" "+n);var k=b.color?"background:"+b.color+";":"",m=b.textColor?"color:"+b.textColor+";":"",l='<div event_id="'+b.id+'" class="'+j+'" style="position:absolute; top:'+f+"px; left:"+c+"px; width:"+(e-c-15)+"px;"+m+""+k+""+(b._text_style||"")+'">',b=a.getEvent(b.id);b._timed&&(l+=a.templates.event_bar_date(b.start_date,
b.end_date,b));l+=a.templates.event_bar_text(b.start_date,b.end_date,b)+"</div>";l+="</div>";i.innerHTML=l;this._rendered.push(i.firstChild);d.appendChild(i.firstChild)};a._locate_event=function(b){for(var a=null;b&&!a&&b.getAttribute;)a=b.getAttribute("event_id"),b=b.parentNode;return a};a.edit=function(b){if(this._edit_id!=b)this.editStop(!1,b),this._edit_id=b,this.updateEvent(b)};a.editStop=function(b,a){if(!(a&&this._edit_id==a)){var c=this.getEvent(this._edit_id);if(c){if(b)c.text=this._editor.value;
this._editor=this._edit_id=null;this.updateEvent(c.id);this._edit_stop_event(c,b)}}};a._edit_stop_event=function(b,a){this._new_event?(a?this.callEvent("onEventAdded",[b.id,b]):b&&this.deleteEvent(b.id,!0),this._new_event=null):a&&this.callEvent("onEventChanged",[b.id,b])};a.getEvents=function(b,a){var c=[],e;for(e in this._events){var g=this._events[e];g&&(!b&&!a||g.start_date<a&&g.end_date>b)&&c.push(g)}return c};a.getRenderedEvent=function(b){if(b){for(var d=a._rendered,c=0;c<d.length;c++){var e=
d[c];if(e.getAttribute("event_id")==b)return e}return null}};a.showEvent=function(b,d){var c=typeof b=="number"||typeof b=="string"?a.getEvent(b):b,d=d||a._mode;if(c&&(!this.checkEvent("onBeforeEventDisplay")||this.callEvent("onBeforeEventDisplay",[c,d]))){var e=a.config.scroll_hour;a.config.scroll_hour=c.start_date.getHours();var g=a.config.preserve_scroll;a.config.preserve_scroll=!1;var f=c.color,i=c.textColor;if(a.config.highlight_displayed_event)c.color=a.config.displayed_event_color,c.textColor=
a.config.displayed_event_text_color;a.setCurrentView(new Date(c.start_date),d);c.color=f;c.textColor=i;a.config.scroll_hour=e;a.config.preserve_scroll=g;if(a.matrix&&a.matrix[d])a._els.dhx_cal_data[0].scrollTop=getAbsoluteTop(a.getRenderedEvent(c.id));a.callEvent("onAfterEventDisplay",[c,d])}};a._loaded={};a._load=function(b,d){b=b||this._load_url;b+=(b.indexOf("?")==-1?"?":"&")+"timeshift="+(new Date).getTimezoneOffset();this.config.prevent_cache&&(b+="&uid="+this.uid());var c,d=d||this._date;if(this._load_mode){for(var e=
this.templates.load_format,d=this.date[this._load_mode+"_start"](new Date(d.valueOf()));d>this._min_date;)d=this.date.add(d,-1,this._load_mode);c=d;for(var g=!0;c<this._max_date;)c=this.date.add(c,1,this._load_mode),this._loaded[e(d)]&&g?d=this.date.add(d,1,this._load_mode):g=!1;var f=c;do c=f,f=this.date.add(c,-1,this._load_mode);while(f>d&&this._loaded[e(f)]);if(c<=d)return!1;for(dhtmlxAjax.get(b+"&from="+e(d)+"&to="+e(c),function(b){a.on_load(b)});d<c;)this._loaded[e(d)]=!0,d=this.date.add(d,1,
this._load_mode)}else dhtmlxAjax.get(b,function(b){a.on_load(b)});this.callEvent("onXLS",[]);return!0};a.on_load=function(b){var d;d=this._process?this[this._process].parse(b.xmlDoc.responseText):this._magic_parser(b);a._process_loading(d);this.callEvent("onXLE",[])};a._process_loading=function(b){this._not_render=this._loading=!0;for(var a=0;a<b.length;a++)this.callEvent("onEventLoading",[b[a]])&&this.addEvent(b[a]);this._not_render=!1;this._render_wait&&this.render_view_data();this._loading=!1;
this._after_call&&this._after_call();this._after_call=null};a.json={};a.json.parse=function(b){if(typeof b=="string")a._temp=eval("("+b+")"),b=a._temp?a._temp.data||a._temp:[];if(b.dhx_security)dhtmlx.security_key=b.dhx_security;var d=a._temp&&a._temp.collections?a._temp.collections:{},c=!1,e;for(e in d)if(d.hasOwnProperty(e)){var c=!0,g=d[e],f=a.serverList[e];if(f){f.splice(0,f.length);for(var i=0;i<g.length;i++){var j=g[i],n={key:j.value,label:j.label},k;for(k in j)if(j.hasOwnProperty(k)&&!(k==
"value"||k=="label"))n[k]=j[k];f.push(n)}}}c&&a.callEvent("onOptionsLoad",[]);for(var m=[],l=0;l<b.length;l++)b[l].start_date=a.templates.xml_date(b[l].start_date),b[l].end_date=a.templates.xml_date(b[l].end_date),m.push(b[l]);return m};a.parse=function(b,a){this._process=a;this.on_load({xmlDoc:{responseText:b}})};a.load=function(b,a,c){if(typeof a=="string")this._process=a,a=c;this._load_url=b;this._after_call=a;this._load(b,this._date)};a.setLoadMode=function(b){b=="all"&&(b="");this._load_mode=
b};a.refresh=function(){alert("not implemented")};a.serverList=function(b,a){return a?this.serverList[b]=a.slice(0):this.serverList[b]=this.serverList[b]||[]};a._userdata={};a._magic_parser=function(b){var d;if(!b.getXMLTopNode){var c=b.xmlDoc.responseText,b=new dtmlXMLLoaderObject(function(){});b.loadXMLString(c)}d=b.getXMLTopNode("data");if(d.tagName!="data")return[];var e=d.getAttribute("dhx_security");if(e)dhtmlx.security_key=e;for(var g=b.doXPath("//coll_options"),f=0;f<g.length;f++){var i=g[f].getAttribute("for"),
j=this.serverList[i];if(j){j.splice(0,j.length);for(var n=b.doXPath(".//item",g[f]),k=0;k<n.length;k++){for(var m=n[k],l=m.attributes,s={key:n[k].getAttribute("value"),label:n[k].getAttribute("label")},p=0;p<l.length;p++){var o=l[p];if(!(o.nodeName=="value"||o.nodeName=="label"))s[o.nodeName]=o.nodeValue}j.push(s)}}}g.length&&a.callEvent("onOptionsLoad",[]);for(var t=b.doXPath("//userdata"),f=0;f<t.length;f++){var q=this.xmlNodeToJSON(t[f]);this._userdata[q.name]=q.text}var r=[];d=b.doXPath("//event");
for(f=0;f<d.length;f++)r[f]=this.xmlNodeToJSON(d[f]),r[f].text=r[f].text||r[f]._tagvalue,r[f].start_date=this.templates.xml_date(r[f].start_date),r[f].end_date=this.templates.xml_date(r[f].end_date);return r};a.xmlNodeToJSON=function(b){for(var a={},c=0;c<b.attributes.length;c++)a[b.attributes[c].name]=b.attributes[c].value;for(c=0;c<b.childNodes.length;c++){var e=b.childNodes[c];e.nodeType==1&&(a[e.tagName]=e.firstChild?e.firstChild.nodeValue:"")}if(!a.text)a.text=b.firstChild?b.firstChild.nodeValue:
"";return a};a.attachEvent("onXLS",function(){if(this.config.show_loading===!0){var b;b=this.config.show_loading=document.createElement("DIV");b.className="dhx_loading";b.style.left=Math.round((this._x-128)/2)+"px";b.style.top=Math.round((this._y-15)/2)+"px";this._obj.appendChild(b)}});a.attachEvent("onXLE",function(){var b;if((b=this.config.show_loading)&&typeof b=="object")this._obj.removeChild(b),this.config.show_loading=!0});a.ical={parse:function(b){var a=b.match(RegExp(this.c_start+"[^\u000c]*"+
this.c_end,""));if(a.length){a[0]=a[0].replace(/[\r\n]+(?=[a-z \t])/g," ");a[0]=a[0].replace(/\;[^:\r\n]*/g,"");for(var c=[],e,g=RegExp("(?:"+this.e_start+")([^\u000c]*?)(?:"+this.e_end+")","g");e=g.exec(a);){for(var f={},i,j=/[^\r\n]+[\r\n]+/g;i=j.exec(e[1]);)this.parse_param(i.toString(),f);if(f.uid&&!f.id)f.id=f.uid;c.push(f)}return c}},parse_param:function(b,a){var c=b.indexOf(":");if(c!=-1){var e=b.substr(0,c).toLowerCase(),g=b.substr(c+1).replace(/\\\,/g,",").replace(/[\r\n]+$/,"");e=="summary"?
e="text":e=="dtstart"?(e="start_date",g=this.parse_date(g,0,0)):e=="dtend"&&(e="end_date",g=this.parse_date(g,0,0));a[e]=g}},parse_date:function(b,d,c){var e=b.split("T");e[1]&&(d=e[1].substr(0,2),c=e[1].substr(2,2));var g=e[0].substr(0,4),f=parseInt(e[0].substr(4,2),10)-1,i=e[0].substr(6,2);return a.config.server_utc&&!e[1]?new Date(Date.UTC(g,f,i,d,c)):new Date(g,f,i,d,c)},c_start:"BEGIN:VCALENDAR",e_start:"BEGIN:VEVENT",e_end:"END:VEVENT",c_end:"END:VCALENDAR"};a.lightbox={};a.formSection=function(b){for(var d=
this.config.lightbox.sections,c=0;c<d.length;c++)if(d[c].name==b)break;var e=d[c];a._lightbox||a.getLightbox();var g=document.getElementById(e.id),f=g.nextSibling,i={section:e,header:g,node:f,getValue:function(b){return a.form_blocks[e.type].get_value(f,b||{},e)},setValue:function(b,d){return a.form_blocks[e.type].set_value(f,b,d||{},e)}},j=a.lightbox["get_"+e.type+"_control"];return j?j(i):i};a.lightbox.get_template_control=function(b){b.control=b.node;return b};a.lightbox.get_select_control=function(b){b.control=
b.node.getElementsByTagName("select")[0];return b};a.lightbox.get_textarea_control=function(b){b.control=b.node.getElementsByTagName("textarea")[0];return b};a.lightbox.get_time_control=function(b){b.control=b.node.getElementsByTagName("select");return b};a.form_blocks={template:{render:function(b){var a=(b.height||"30")+"px";return"<div class='dhx_cal_ltext dhx_cal_template' style='height:"+a+";'></div>"},set_value:function(b,a){b.innerHTML=a||""},get_value:function(b){return b.innerHTML||""},focus:function(){}},
textarea:{render:function(b){var a=(b.height||"130")+"px";return"<div class='dhx_cal_ltext' style='height:"+a+";'><textarea></textarea></div>"},set_value:function(b,a){b.firstChild.value=a||""},get_value:function(b){return b.firstChild.value},focus:function(b){var a=b.firstChild;a.select();a.focus()}},select:{render:function(b){for(var a=(b.height||"23")+"px",c="<div class='dhx_cal_ltext' style='height:"+a+";'><select style='width:100%;'>",e=0;e<b.options.length;e++)c+="<option value='"+b.options[e].key+
"'>"+b.options[e].label+"</option>";c+="</select></div>";return c},set_value:function(b,a,c,e){var g=b.firstChild;if(!g._dhx_onchange&&e.onchange)g.onchange=e.onchange,g._dhx_onchange=!0;if(typeof a=="undefined")a=(g.options[0]||{}).value;g.value=a||""},get_value:function(b){return b.firstChild.value},focus:function(b){var a=b.firstChild;a.select&&a.select();a.focus()}},time:{render:function(b){var d=a.config,c=this.date.date_part(new Date),e=1440,g=0;a.config.limit_time_select&&(e=60*d.last_hour+
1,g=60*d.first_hour,c.setHours(d.first_hour));var f="<select>",i=g,j=c.getDate();for(b._time_values=[];i<e;){var n=this.templates.time_picker(c);f+="<option value='"+i+"'>"+n+"</option>";b._time_values.push(i);c.setTime(c.valueOf()+this.config.time_step*6E4);var k=c.getDate()!=j?1:0,i=k*1440+c.getHours()*60+c.getMinutes()}f+="</select> <select>";for(i=1;i<32;i++)f+="<option value='"+i+"'>"+i+"</option>";f+="</select> <select>";for(i=0;i<12;i++)f+="<option value='"+i+"'>"+this.locale.date.month_full[i]+
"</option>";f+="</select> <select>";c=c.getFullYear()-5;for(i=0;i<10;i++)f+="<option value='"+(c+i)+"'>"+(c+i)+"</option>";f+="</select> ";return"<div style='height:30px;padding-top:0px;font-size:inherit;' class='dhx_section_time'>"+f+"<span style='font-weight:normal; font-size:10pt;'> &nbsp;&ndash;&nbsp; </span>"+f+"</div>"},set_value:function(b,d,c,e){function g(b,a,d){for(var c=e._time_values,f=d.getHours()*60+d.getMinutes(),g=f,i=!1,j=0;j<c.length;j++){var k=c[j];if(k===f){i=!0;break}k<f&&(g=
k)}b[a+0].value=i?f:g;b[a+1].value=d.getDate();b[a+2].value=d.getMonth();b[a+3].value=d.getFullYear()}var f=a.config,i=b.getElementsByTagName("select");if(f.full_day){if(!b._full_day){var j="<label class='dhx_fullday'><input type='checkbox' name='full_day' value='true'> "+a.locale.labels.full_day+"&nbsp;</label></input>";a.config.wide_form||(j=b.previousSibling.innerHTML+j);b.previousSibling.innerHTML=j;b._full_day=!0}var n=b.previousSibling.getElementsByTagName("input")[0];n.checked=a.date.time_part(c.start_date)===
0&&a.date.time_part(c.end_date)===0;i[0].disabled=n.checked;i[i.length/2].disabled=n.checked;n.onclick=function(){if(n.checked){var d={};a.form_blocks.time.get_value(b,d);var e=a.date.date_part(d.start_date),f=a.date.date_part(d.end_date);if(+f==+e||+f>=+e&&(c.end_date.getHours()!=0||c.end_date.getMinutes()!=0))f=a.date.add(f,1,"day")}i[0].disabled=n.checked;i[i.length/2].disabled=n.checked;g(i,0,e||c.start_date);g(i,4,f||c.end_date)}}if(f.auto_end_date&&f.event_duration)for(var k=function(){var b=
new Date(i[3].value,i[2].value,i[1].value,0,i[0].value),d=new Date(b.getTime()+a.config.event_duration*6E4);g(i,4,d)},m=0;m<4;m++)i[m].onchange=k;g(i,0,c.start_date);g(i,4,c.end_date)},get_value:function(b,d){s=b.getElementsByTagName("select");d.start_date=new Date(s[3].value,s[2].value,s[1].value,0,s[0].value);d.end_date=new Date(s[7].value,s[6].value,s[5].value,0,s[4].value);if(d.end_date<=d.start_date)d.end_date=a.date.add(d.start_date,a.config.time_step,"minute");return{start_date:new Date(d.start_date),
end_date:new Date(d.end_date)}},focus:function(b){b.getElementsByTagName("select")[0].focus()}}};a.showCover=function(b){if(b){b.style.display="block";var a=window.pageYOffset||document.body.scrollTop||document.documentElement.scrollTop,c=window.pageXOffset||document.body.scrollLeft||document.documentElement.scrollLeft,e=window.innerHeight||document.documentElement.clientHeight;b.style.top=a?Math.round(a+Math.max((e-b.offsetHeight)/2,0))+"px":Math.round(Math.max((e-b.offsetHeight)/2,0)+9)+"px";b.style.left=
document.documentElement.scrollWidth>document.body.offsetWidth?Math.round(c+(document.body.offsetWidth-b.offsetWidth)/2)+"px":Math.round((document.body.offsetWidth-b.offsetWidth)/2)+"px"}this.show_cover()};a.showLightbox=function(b){if(b)if(this.callEvent("onBeforeLightbox",[b])){var a=this.getLightbox();this.showCover(a);this._fill_lightbox(b,a);this.callEvent("onLightbox",[b])}else if(this._new_event)this._new_event=null};a._fill_lightbox=function(b,d){var c=this.getEvent(b),e=d.getElementsByTagName("span");
a.templates.lightbox_header?(e[1].innerHTML="",e[2].innerHTML=a.templates.lightbox_header(c.start_date,c.end_date,c)):(e[1].innerHTML=this.templates.event_header(c.start_date,c.end_date,c),e[2].innerHTML=(this.templates.event_bar_text(c.start_date,c.end_date,c)||"").substr(0,70));for(var g=this.config.lightbox.sections,f=0;f<g.length;f++){var i=g[f],j=document.getElementById(i.id).nextSibling,n=this.form_blocks[i.type],k=c[i.map_to]!==void 0?c[i.map_to]:i.default_value;n.set_value.call(this,j,k,c,
i);g[f].focus&&n.focus.call(this,j)}a._lightbox_id=b};a._lightbox_out=function(b){for(var a=this.config.lightbox.sections,c=0;c<a.length;c++){var e=document.getElementById(a[c].id),e=e?e.nextSibling:e,g=this.form_blocks[a[c].type],f=g.get_value.call(this,e,b,a[c]);a[c].map_to!="auto"&&(b[a[c].map_to]=f)}return b};a._empty_lightbox=function(b){var d=a._lightbox_id,c=this.getEvent(d),e=this.getLightbox();this._lame_copy(c,b);c._timed=this.is_one_day_event(c);this.setEvent(c.id,c);this._edit_stop_event(c,
!0);this.render_view_data()};a.hide_lightbox=function(){this.hideCover(this.getLightbox());this._lightbox_id=null;this.callEvent("onAfterLightbox",[])};a.hideCover=function(b){if(b)b.style.display="none";this.hide_cover()};a.hide_cover=function(){this._cover&&this._cover.parentNode.removeChild(this._cover);this._cover=null};a.show_cover=function(){this._cover=document.createElement("DIV");this._cover.className="dhx_cal_cover";var b=document.height!==void 0?document.height:document.body.offsetHeight,
a=document.documentElement?document.documentElement.scrollHeight:0;this._cover.style.height=Math.max(b,a)+"px";document.body.appendChild(this._cover)};a.save_lightbox=function(){var b=this._lightbox_out({},this._lame_copy(this.getEvent(this._lightbox_id)));if(!this.checkEvent("onEventSave")||this.callEvent("onEventSave",[this._lightbox_id,b,this._new_event]))this._empty_lightbox(b),this.hide_lightbox()};a.startLightbox=function(b,a){this._lightbox_id=b;this._lightbox=a;this.showCover(a)};a.endLightbox=
function(b,d){this._edit_stop_event(a.getEvent(this._lightbox_id),b);b&&a.render_view_data();this.hideCover(d);this._lightbox_id=null};a.resetLightbox=function(){a._lightbox&&a._lightbox.parentNode.removeChild(a._lightbox);a._lightbox=null};a.cancel_lightbox=function(){this.callEvent("onEventCancel",[this._lightbox_id,this._new_event]);this.endLightbox(!1);this.hide_lightbox()};a._init_lightbox_events=function(){this.getLightbox().onclick=function(b){var d=b?b.target:event.srcElement;if(!d.className)d=
d.previousSibling;if(d&&d.className)switch(d.className){case "dhx_save_btn":a.save_lightbox();break;case "dhx_delete_btn":var c=a.locale.labels.confirm_deleting;a._dhtmlx_confirm(c,a.locale.labels.title_confirm_deleting,function(){a.deleteEvent(a._lightbox_id);a._new_event=null;a.hide_lightbox()});break;case "dhx_cancel_btn":a.cancel_lightbox();break;default:if(d.getAttribute("dhx_button"))a.callEvent("onLightboxButton",[d.className,d,b]);else{var e,g,f;if(d.className.indexOf("dhx_custom_button")!=
-1)d.className.indexOf("dhx_custom_button_")!=-1?(e=d.parentNode.getAttribute("index"),f=d.parentNode.parentNode):(e=d.getAttribute("index"),f=d.parentNode,d=d.firstChild);e&&(g=a.form_blocks[a.config.lightbox.sections[e].type],g.button_click(e,d,f,f.nextSibling))}}};this.getLightbox().onkeydown=function(b){switch((b||event).keyCode){case a.keys.edit_save:if((b||event).shiftKey)break;a.save_lightbox();break;case a.keys.edit_cancel:a.cancel_lightbox()}}};a.setLightboxSize=function(){var b=this._lightbox;
if(b){var d=b.childNodes[1];d.style.height="0px";d.style.height=d.scrollHeight+"px";b.style.height=d.scrollHeight+a.xy.lightbox_additional_height+"px";d.style.height=d.scrollHeight+"px"}};a._init_dnd_events=function(){dhtmlxEvent(document.body,"mousemove",a._move_while_dnd);dhtmlxEvent(document.body,"mouseup",a._finish_dnd);a._init_dnd_events=function(){}};a._move_while_dnd=function(b){if(a._dnd_start_lb){if(!document.dhx_unselectable)document.body.className+=" dhx_unselectable",document.dhx_unselectable=
!0;var d=a.getLightbox(),c=b&&b.target?[b.pageX,b.pageY]:[event.clientX,event.clientY];d.style.top=a._lb_start[1]+c[1]-a._dnd_start_lb[1]+"px";d.style.left=a._lb_start[0]+c[0]-a._dnd_start_lb[0]+"px"}};a._ready_to_dnd=function(b){var d=a.getLightbox();a._lb_start=[parseInt(d.style.left,10),parseInt(d.style.top,10)];a._dnd_start_lb=b&&b.target?[b.pageX,b.pageY]:[event.clientX,event.clientY]};a._finish_dnd=function(){if(a._lb_start)a._lb_start=a._dnd_start_lb=!1,document.body.className=document.body.className.replace(" dhx_unselectable",
""),document.dhx_unselectable=!1};a.getLightbox=function(){if(!this._lightbox){var b=document.createElement("DIV");b.className="dhx_cal_light";a.config.wide_form&&(b.className+=" dhx_cal_light_wide");a.form_blocks.recurring&&(b.className+=" dhx_cal_light_rec");/msie|MSIE 6/.test(navigator.userAgent)&&(b.className+=" dhx_ie6");b.style.visibility="hidden";for(var d=this._lightbox_template,c=this.config.buttons_left,e=0;e<c.length;e++)d+="<div class='dhx_btn_set dhx_left_btn_set "+c[e]+"_set'><div dhx_button='1' class='"+
c[e]+"'></div><div>"+a.locale.labels[c[e]]+"</div></div>";c=this.config.buttons_right;for(e=0;e<c.length;e++)d+="<div class='dhx_btn_set dhx_right_btn_set "+c[e]+"_set' style='float:right;'><div dhx_button='1' class='"+c[e]+"'></div><div>"+a.locale.labels[c[e]]+"</div></div>";d+="</div>";b.innerHTML=d;if(a.config.drag_lightbox)b.firstChild.onmousedown=a._ready_to_dnd,b.firstChild.onselectstart=function(){return!1},b.firstChild.style.cursor="pointer",a._init_dnd_events();document.body.insertBefore(b,
document.body.firstChild);this._lightbox=b;for(var g=this.config.lightbox.sections,d="",e=0;e<g.length;e++){var f=this.form_blocks[g[e].type];if(f){g[e].id="area_"+this.uid();var i="";g[e].button&&(i="<div class='dhx_custom_button' index='"+e+"'><div class='dhx_custom_button_"+g[e].button+"'></div><div>"+this.locale.labels["button_"+g[e].button]+"</div></div>");this.config.wide_form&&(d+="<div class='dhx_wrap_section'>");d+="<div id='"+g[e].id+"' class='dhx_cal_lsection'>"+i+this.locale.labels["section_"+
g[e].name]+"</div>"+f.render.call(this,g[e]);d+="</div>"}}for(var j=b.getElementsByTagName("div"),e=0;e<j.length;e++){var n=j[e];if(n.className=="dhx_cal_larea"){n.innerHTML=d;break}}this.setLightboxSize();this._init_lightbox_events(this);b.style.display="none";b.style.visibility="visible"}return this._lightbox};a._lightbox_template="<div class='dhx_cal_ltitle'><span class='dhx_mark'>&nbsp;</span><span class='dhx_time'></span><span class='dhx_title'></span></div><div class='dhx_cal_larea'></div>";
a._dp_init=function(b){b._methods=["setEventTextStyle","","changeEventId","deleteEvent"];this.attachEvent("onEventAdded",function(a){!this._loading&&this.validId(a)&&b.setUpdated(a,!0,"inserted")});this.attachEvent("onConfirmedBeforeEventDelete",function(a){if(this.validId(a)){var c=b.getState(a);if(c=="inserted"||this._new_event)return b.setUpdated(a,!1),!0;if(c=="deleted")return!1;if(c=="true_deleted")return!0;b.setUpdated(a,!0,"deleted");return!1}});this.attachEvent("onEventChanged",function(a){!this._loading&&
this.validId(a)&&b.setUpdated(a,!0,"updated")});b._getRowData=function(a){var b=this.obj.getEvent(a),e={},g;for(g in b)g.indexOf("_")!=0&&(e[g]=b[g]&&b[g].getUTCFullYear?this.obj.templates.xml_format(b[g]):b[g]);return e};b._clearUpdateFlag=function(){};b.attachEvent("insertCallback",a._update_callback);b.attachEvent("updateCallback",a._update_callback);b.attachEvent("deleteCallback",function(a,b){this.obj.setUserData(b,this.action_param,"true_deleted");this.obj.deleteEvent(b)})};a.setUserData=function(a,
d,c){a?this.getEvent(a)[d]=c:this._userdata[d]=c};a.getUserData=function(a,d){return a?this.getEvent(a)[d]:this._userdata[d]};a.setEventTextStyle=function(a,d){this.for_rendered(a,function(a){a.style.cssText+=";"+d});var c=this.getEvent(a);c._text_style=d;this.event_updated(c)};a.validId=function(){return!0};a._update_callback=function(b){var d=a.xmlNodeToJSON(b.firstChild);d.text=d.text||d._tagvalue;d.start_date=a.templates.xml_date(d.start_date);d.end_date=a.templates.xml_date(d.end_date);a.addEvent(d)};
for(var e=0;e<Scheduler._schedulerPlugins.length;e++)Scheduler._schedulerPlugins[e](a);a._internal_id=Scheduler._seed++;Scheduler.$syncFactory&&Scheduler.$syncFactory(a);return a};window.scheduler=Scheduler.getSchedulerInstance();
if(dhtmlx&&dhtmlx.attaches)dhtmlx.attaches.attachScheduler=function(a,e,b,d){var b=b||'<div class="dhx_cal_tab" name="day_tab" style="right:204px;"></div><div class="dhx_cal_tab" name="week_tab" style="right:140px;"></div><div class="dhx_cal_tab" name="month_tab" style="right:76px;"></div>',c=document.createElement("DIV");c.id="dhxSchedObj_"+this._genStr(12);c.innerHTML='<div id="'+c.id+'" class="dhx_cal_container" style="width:100%; height:100%;"><div class="dhx_cal_navline"><div class="dhx_cal_prev_button">&nbsp;</div><div class="dhx_cal_next_button">&nbsp;</div><div class="dhx_cal_today_button"></div><div class="dhx_cal_date"></div>'+
b+'</div><div class="dhx_cal_header"></div><div class="dhx_cal_data"></div></div>';document.body.appendChild(c.firstChild);this.attachObject(c.id,!1,!0);this.vs[this.av].sched=d;this.vs[this.av].schedId=c.id;d.setSizes=d.update_view;d.destructor=function(){};d.init(c.id,a,e);return this.vs[this._viewRestore()].sched};
