/*
Copyright DHTMLX LTD. http://www.dhtmlx.com
To use this component please contact sales@dhtmlx.com to obtain license
*/
Scheduler.plugin(function(a){a.config.limit_start=null;a.config.limit_end=null;a.config.limit_view=!1;a.config.check_limits=!0;a.config.mark_now=!0;a.config.display_marked_timespans=!0;(function(){var v=null,t="dhx_time_block",G=function(a,b,c){b instanceof Date&&c instanceof Date?(a.start_date=b,a.end_date=c):(a.days=b,a.zones=c);return a},F=function(a,b,c){var d=typeof a=="object"?a:{days:a};d.type=t;d.css="";if(b){if(c)d.sections=c;d=G(d,a,b)}return d};a.blockTime=function(e,b,c){var d=F(e,b,c);
return a.addMarkedTimespan(d)};a.unblockTime=function(e,b,c){var b=b||"fullday",d=F(e,b,c);return a.deleteMarkedTimespan(d)};a.attachEvent("onBeforeViewChange",function(e,b,c,d){d=d||b;c=c||e;return a.config.limit_view&&(d.valueOf()>a.config.limit_end.valueOf()||this.date.add(d,1,c)<=a.config.limit_start.valueOf())?(setTimeout(function(){a.setCurrentView(a._date,c)},1),!1):!0});var y=function(a,b,c){var d=c[b]&&c[b][t]?c[b][t]:c[a]&&c[a][t]?c[a][t]:[];return d},u=function(e){if(!e)return!0;if(!a.config.check_limits)return!0;
for(var b=a,c=b._mode,d=a._marked_timespans,f=b.config,i=[],i=e.rec_type?a.getRecDates(e):[e],h=!0,j=0;j<i.length;j++){var g=i[j];if(h=f.limit_start&&f.limit_end?g.start_date.valueOf()>=f.limit_start.valueOf()&&g.end_date.valueOf()<=f.limit_end.valueOf():!0)for(var k=new Date(g.start_date.valueOf()),q=a.date.add(k,1,"day");k<g.end_date;k=a.date.date_part(q),q=b.date.add(k,1,"day")){var o=+a.date.date_part(new Date(k)),p=k.getDay(),l=[];if(b._props&&b._props[c]){var n=b._props[c],r=d[c];if(r&&r[g[n.map_to]])for(var s=
r[g[n.map_to]],w=y(p,o,s),m=0;m<w.length;m++)l=a._add_timespan_zones(l,w[m].zones)}if(b.matrix&&b.matrix[c]){var t=b.matrix[c],u=d[c];if(u&&u[g[t.y_property]])for(var v=u[g[t.y_property]],B=y(p,o,v),m=0;m<B.length;m++)l=a._add_timespan_zones(l,B[m].zones)}for(var E=d.global,C=y(p,o,E),m=0;m<C.length;m++)l=a._add_timespan_zones(l,C[m].zones);var D=a._get_zone_minutes(k),z=g.end_date>q||g.end_date.getDate()!=k.getDate()?1440:a._get_zone_minutes(g.end_date);if(l)for(m=0;m<l.length;m+=2){var A=l[m],x=
l[m+1];if(A<z&&x>D){if(D<=x&&D>=A){if(x==1440||z<x){h=!1;break}if(g._timed&&b._drag_id&&b._drag_mode=="new-size")g.start_date.setHours(0),g.start_date.setMinutes(x);else{h=!1;break}}if(z>=A&&z<x||D<A&&z>x)if(g._timed&&b._drag_id&&b._drag_mode=="new-size")g.end_date.setHours(0),g.end_date.setMinutes(A);else{h=!1;break}}}}if(!h)b._drag_id=null,b._drag_mode=null,h=b.checkEvent("onLimitViolation")?b.callEvent("onLimitViolation",[g.id,g]):h}return h};a.attachEvent("onMouseDown",function(a){return!(a=t)});
a.attachEvent("onBeforeDrag",function(e){return!e?!0:u(a.getEvent(e))});a.attachEvent("onClick",function(e){return u(a.getEvent(e))});a.attachEvent("onBeforeLightbox",function(e){var b=a.getEvent(e);v=[b.start_date,b.end_date];return u(b)});a.attachEvent("onEventSave",function(e,b){if(b.rec_type){var c=a._lame_clone(b);a._roll_back_dates(c)}return u(b)});a.attachEvent("onEventAdded",function(e){if(!e)return!0;var b=a.getEvent(e);if(!u(b)&&a.config.limit_start&&a.config.limit_end){if(b.start_date<
a.config.limit_start)b.start_date=new Date(a.config.limit_start);if(b.start_date.valueOf()>=a.config.limit_end.valueOf())b.start_date=this.date.add(a.config.limit_end,-1,"day");if(b.end_date<a.config.limit_start)b.end_date=new Date(a.config.limit_start);if(b.end_date.valueOf()>=a.config.limit_end.valueOf())b.end_date=this.date.add(a.config.limit_end,-1,"day");if(b.start_date.valueOf()>=b.end_date.valueOf())b.end_date=this.date.add(b.start_date,this.config.event_duration||this.config.time_step,"minute");
b._timed=this.is_one_day_event(b)}return!0});a.attachEvent("onEventChanged",function(e){if(!e)return!0;var b=a.getEvent(e);if(!u(b)){if(!v)return!1;b.start_date=v[0];b.end_date=v[1];b._timed=this.is_one_day_event(b)}return!0});a.attachEvent("onBeforeEventChanged",function(a){return u(a)});a.attachEvent("onBeforeEventCreated",function(e){var b=a.getActionData(e).date,c={_timed:!0,start_date:b,end_date:a.date.add(b,a.config.time_step,"minute")};return u(c)});a.attachEvent("onViewChange",function(){a.markNow()});
a.attachEvent("onSchedulerResize",function(){window.setTimeout(function(){a.markNow()},1);return!0});a.attachEvent("onTemplatesReady",function(){a._mark_now_timer=window.setInterval(function(){a.markNow()},6E4)});a.markNow=function(e){var b="dhx_now_time";this._els[b]||(this._els[b]=[]);var c=a.config.now_date||new Date,d=this.config;a._remove_mark_now();if(!e&&d.mark_now&&c<this._max_date&&c>this._min_date&&c.getHours()>=d.first_hour&&c.getHours()<d.last_hour){var f=this.locate_holder_day(c);this._els[b]=
a._append_mark_now(f,c)}};a._append_mark_now=function(e,b){var c="dhx_now_time",d=a._get_zone_minutes(b),f={zones:[d,d+1],css:c,type:c};if(this._table_view){if(this._mode=="month")return f.days=+a.date.date_part(b),a._render_marked_timespan(f,null,null)}else if(this._props&&this._props[this._mode]){for(var i=this._els.dhx_cal_data[0].childNodes,h=[],j=0;j<i.length-1;j++){var g=e+j;f.days=g;var k=a._render_marked_timespan(f,null,g)[0];h.push(k)}return h}else return f.days=e,a._render_marked_timespan(f,
null,e)};a._remove_mark_now=function(){for(var a="dhx_now_time",b=this._els[a],c=0;c<b.length;c++){var d=b[c],f=d.parentNode;f&&f.removeChild(d)}this._els[a]=[]};a._marked_timespans={global:{}};a._get_zone_minutes=function(a){return a.getHours()*60+a.getMinutes()};a._prepare_timespan_options=function(e){var b=[],c=[];if(e.days=="fullweek")e.days=[0,1,2,3,4,5,6];if(e.days instanceof Array){for(var d=e.days.slice(),f=0;f<d.length;f++){var i=a._lame_clone(e);i.days=d[f];b.push.apply(b,a._prepare_timespan_options(i))}return b}if(!e||
!(e.start_date&&e.end_date&&e.end_date>e.start_date||e.days!==void 0&&e.zones))return b;var h=0,j=1440;if(e.zones=="fullday")e.zones=[h,j];if(e.zones&&e.invert_zones)e.zones=a.invertZones(e.zones);e.id=a.uid();e.css=e.css||"";e.type=e.type||"default";var g=e.sections;if(g)for(var k in g){if(g.hasOwnProperty(k)){var q=g[k];q instanceof Array||(q=[q]);for(f=0;f<q.length;f++){var o=a._lame_copy({},e);o.sections={};o.sections[k]=q[f];c.push(o)}}}else c.push(e);for(var p=0;p<c.length;p++){var l=c[p],n=
l.start_date,r=l.end_date;if(n&&r)for(var s=a.date.date_part(new Date(n)),w=a.date.add(s,1,"day");s<r;){o=a._lame_copy({},l);delete o.start_date;delete o.end_date;o.days=s.valueOf();var m=n>s?a._get_zone_minutes(n):h,t=r>w||r.getDate()!=s.getDate()?j:a._get_zone_minutes(r);o.zones=[m,t];b.push(o);s=w;w=a.date.add(w,1,"day")}else{if(l.days instanceof Date)l.days=a.date.date_part(l.days).valueOf();l.zones=e.zones.slice();b.push(l)}}return b};a._get_dates_by_index=function(e,b,c){for(var d=[],b=b||a._min_date,
c=c||a._max_date,f=b.getDay(),i=e-f>=0?e-f:7-b.getDay()+e,h=a.date.add(b,i,"day");h<c;h=a.date.add(h,1,"week"))d.push(h);return d};a._get_css_classes_by_config=function(a){var b=[];a.type==t&&(b.push(t),a.css&&b.push(t+"_reset"));b.push("dhx_marked_timespan",a.css);return b.join(" ")};a._get_block_by_config=function(a){var b=document.createElement("DIV");if(a.html)typeof a.html=="string"?b.innerHTML=a.html:b.appendChild(a.html);return b};a._render_marked_timespan=function(e,b,c){var d=[],f=a.config,
i=this._min_date,h=this._max_date,j=!1;if(!f.display_marked_timespans)return d;if(!c&&c!==0)if(e.days<7)c=e.days;else{var g=new Date(e.days),j=+g;if(!(+h>=+g&&+i<=+g))return d;var k=g.getDay(),c=a.config.start_on_monday?k==0?6:k-1:k}var q=e.zones,o=a._get_css_classes_by_config(e);if(a._table_view&&a._mode=="month"){var p=[],l=[];if(b)p.push(b),l.push(c);else for(var l=j?[j]:a._get_dates_by_index(c),n=0;n<l.length;n++)p.push(this._scales[l[n]]);for(n=0;n<p.length;n++)for(var b=p[n],c=l[n],r=0;r<q.length;r+=
2){var s=q[n],t=q[n+1];if(t<=s)return[];var m=a._get_block_by_config(e);m.className=o;var u=b.offsetHeight-1,v=b.offsetWidth-1,y=Math.floor((this._correct_shift(c,1)-i.valueOf())/(864E5*this._cols.length)),B=this.locate_holder_day(c,!1)%this._cols.length,E=this._colsS[B],C=this._colsS.heights[y]+(this._colsS.height?this.xy.month_scale_height+2:2)-1;m.style.top=C+"px";m.style.lineHeight=m.style.height=u+"px";m.style.left=E+Math.round(s/1440*v)+"px";m.style.width=Math.round((t-s)/1440*v)+"px";b.appendChild(m);
d.push(m)}}else{b=b?b:a.locate_holder(c);for(n=0;n<q.length;n+=2){s=Math.max(q[n],f.first_hour*60);t=Math.min(q[n+1],f.last_hour*60);if(t<=s)return[];m=a._get_block_by_config(e);m.className=o;m.style.top=Math.round((s*6E4-this.config.first_hour*36E5)*this.config.hour_size_px/36E5)%(this.config.hour_size_px*24)+"px";m.style.lineHeight=m.style.height=Math.max(Math.round((t-s-1)*6E4*this.config.hour_size_px/36E5)%(this.config.hour_size_px*24),1)+"px";b.appendChild(m);d.push(m)}}return d};a.markTimespan=
function(e){var b=a._prepare_timespan_options(e);if(b.length){for(var c=[],d=0;d<b.length;d++){var f=b[d],i=a._render_marked_timespan(f,null,null);i.length&&c.push.apply(c,i)}return c}};a.unmarkTimespan=function(a){if(a)for(var b=0;b<a.length;b++){var c=a[b];c.parentNode.removeChild(c)}};a._marked_timespans_ids={};a.addMarkedTimespan=function(e){var b=a._prepare_timespan_options(e),c="global";if(b.length){var d=b[0].id,f=a._marked_timespans,i=a._marked_timespans_ids;i[d]||(i[d]=[]);for(var h=0;h<
b.length;h++){var j=b[h],g=j.days,k=j.zones,q=j.css,o=j.sections,p=j.type;if(o)for(var l in o){if(o.hasOwnProperty(l)){f[l]||(f[l]={});var n=o[l],r=f[l];r[n]||(r[n]={});r[n][g]||(r[n][g]={});r[n][g][p]||(r[n][g][p]=[]);var s=r[n][g][p];j._array=s;s.push(j);i[d].push(j)}}else f[c][g]||(f[c][g]={}),f[c][g][p]||(f[c][g][p]=[]),s=f[c][g][p],j._array=s,s.push(j),i[d].push(j)}return d}};a._add_timespan_zones=function(a,b){var c=a.slice(),b=b.slice();if(!c.length)return b;for(var d=0;d<c.length;d+=2)for(var f=
c[d],i=c[d+1],h=d+2==c.length,j=0;j<b.length;j+=2){var g=b[j],k=b[j+1];if(k>i&&g<=i||g<f&&k>=f)c[d]=Math.min(f,g),c[d+1]=Math.max(i,k),d-=2;else{if(!h)continue;var q=f>g?0:2;c.splice(d+q,0,g,k)}b.splice(j--,2);break}return c};a._subtract_timespan_zones=function(a,b){for(var c=a.slice(),d=0;d<c.length;d+=2)for(var f=c[d],i=c[d+1],h=0;h<b.length;h+=2){var j=b[h],g=b[h+1];if(g>f&&j<i){var k=!1;f>=j&&i<=g&&c.splice(d,2);f<j&&(c.splice(d,2,f,j),k=!0);i>g&&c.splice(k?d+2:d,k?0:2,g,i);d-=2;break}}return c};
a.invertZones=function(e){return a._subtract_timespan_zones([0,1440],e.slice())};a._delete_marked_timespan_by_id=function(e){var b=a._marked_timespans_ids[e];if(b)for(var c=0;c<b.length;c++)for(var d=b[c],f=d._array,i=0;i<f.length;i++)if(f[i]==d){f.splice(i,1);break}};a._delete_marked_timespan_by_config=function(e){var b=a._marked_timespans,c=e.sections,d=e.days,f=e.type||"default",i=[];if(c)for(var h in c){if(c.hasOwnProperty(h)&&b[h]){var j=c[h];b[h][j]&&b[h][j][d]&&b[h][j][d][f]&&(i=b[h][j][d][f])}}else b.global[d]&&
b.global[d][f]&&(i=b.global[d][f]);for(var g=0;g<i.length;g++){var k=i[g],q=a._subtract_timespan_zones(k.zones,e.zones);if(q.length)k.zones=q;else{i.splice(g,1);g--;for(var o=a._marked_timespans_ids[k.id],p=0;p<o.length;p++)if(o[p]==k){o.splice(p,1);break}}}};a.deleteMarkedTimespan=function(e){if(!arguments.length)a._marked_timespans={global:{}};if(typeof e!="object")a._delete_marked_timespan_by_id(e);else for(var b=a._prepare_timespan_options(e),c=0;c<b.length;c++){var d=b[c];a._delete_marked_timespan_by_config(b[c])}};
a._get_types_to_render=function(a,b){var c=a?a:{},d;for(d in b||{})b.hasOwnProperty(d)&&(c[d]=b[d]);return c};a._get_configs_to_render=function(a){var b=[],c;for(c in a)a.hasOwnProperty(c)&&b.push.apply(b,a[c]);return b};a.attachEvent("onScaleAdd",function(e,b){if(!(a._table_view&&a._mode!="month")){var c=b.getDay(),d=b.valueOf(),f=this._mode,i=a._marked_timespans,h=[];if(this._props&&this._props[f]){var j=this._props[f],g=j.options,k=(j.position||0)+Math.floor((this._correct_shift(b.valueOf(),1)-
this._min_date.valueOf())/864E5),q=g[k],b=a.date.date_part(new Date(this._date)),c=b.getDay(),d=b.valueOf();if(i[f]&&i[f][q.key]){var o=i[f][q.key],p=a._get_types_to_render(o[c],o[d]);h.push.apply(h,a._get_configs_to_render(p))}}var l=i.global,n=l[d]||l[c];h.push.apply(h,a._get_configs_to_render(n));for(var r=0;r<h.length;r++)a._render_marked_timespan(h[r],e,b)}})})()});
