/*
Copyright DHTMLX LTD. http://www.dhtmlx.com
To use this component please contact sales@dhtmlx.com to obtain license
*/
Scheduler.plugin(function(c){(function(){c.config.all_timed="short";c.config.update_render=!0;var j=function(a){return!((a.end_date-a.start_date)/36E5>=24)},k=c._pre_render_events_line;c._pre_render_events_line=function(a,i){if(!this.config.all_timed)return k.call(this,a,i);for(var d=0;d<a.length;d++){var e=a[d];if(!e._timed)if(this.config.all_timed=="short"&&!j(e))a.splice(d--,1);else{var b=this._lame_copy({},e);b.start_date=new Date(b.start_date);var h=c.date.add(e.start_date,1,"day"),h=c.date.date_part(h);
if(e.end_date<h)b.end_date=new Date(e.end_date);else if(b.end_date=h,this.config.last_hour!=24)b.end_date=c.date.date_part(new Date(b.start_date)),b.end_date.setHours(this.config.last_hour);var g=!1;b.start_date<this._max_date&&b.end_date>this._min_date&&b.start_date<b.end_date&&(a[d]=b,g=!0);b.start_date>b.end_date&&a.splice(d--,1);var f=this._lame_copy({},e);f.end_date=new Date(f.end_date);f.start_date=f.start_date<this._min_date?new Date(this._min_date):this.date.add(e.start_date,1,"day");f.start_date.setHours(this.config.first_hour);
f.start_date.setMinutes(0);f.start_date<this._max_date&&f.start_date<f.end_date&&(g?a.splice(d+1,0,f):a[d--]=f)}}var l=this._drag_mode=="move"?!1:i;return k.call(this,a,l)};var g=c.get_visible_events;c.get_visible_events=function(a){return!this.config.all_timed?g.call(this,a):g.call(this,!1)};c.attachEvent("onBeforeViewChange",function(a,i,d){c._allow_dnd=d=="day"||d=="week";return!0});c.render_view_data=function(a,c){if(!a){if(this._not_render){this._render_wait=!0;return}this._render_wait=!1;this.clear_view();
a=this.get_visible_events(!(this._table_view||this.config.multi_day))}if(this.config.multi_day&&!this._table_view){for(var d=[],e=[],b=0;b<a.length;b++)a[b]._timed||this.config.all_timed===!0||this.config.all_timed=="short"&&j(a[b])?d.push(a[b]):e.push(a[b]);this._rendered_location=this._els.dhx_cal_data[0];this._table_view=!1;this.render_data(d,c);this._rendered_location=this._els.dhx_multi_day[0];this._table_view=!0;this.render_data(e,c);this._table_view=!1}else this._rendered_location=this._els.dhx_cal_data[0],
this.render_data(a,c)}})()});
