/*
Copyright DHTMLX LTD. http://www.dhtmlx.com
To use this component please contact sales@dhtmlx.com to obtain license
*/
Scheduler.plugin(function(b){b._props={};b.createUnitsView=function(a,g,k,f,l,m){if(typeof a=="object")k=a.list,g=a.property,f=a.size||0,l=a.step||1,m=a.skip_incorrect,a=a.name;b._props[a]={map_to:g,options:k,step:l,position:0};if(f>b._props[a].options.length)b._props[a]._original_size=f,f=0;b._props[a].size=f;b._props[a].skip_incorrect=m||!1;b.date[a+"_start"]=b.date.day_start;b.templates[a+"_date"]=function(a){return b.templates.day_date(a)};b.templates[a+"_scale_date"]=function(d){var i=b._props[a].options;
if(!i.length)return"";var g=(b._props[a].position||0)+Math.floor((b._correct_shift(d.valueOf(),1)-b._min_date.valueOf())/864E5);return i[g].css?"<span class='"+i[g].css+"'>"+i[g].label+"</span>":i[g].label};b.date["add_"+a]=function(a,g){return b.date.add(a,g,"day")};b.date["get_"+a+"_end"]=function(d){return b.date.add(d,b._props[a].size||b._props[a].options.length,"day")};b.attachEvent("onOptionsLoad",function(){for(var d=b._props[a],g=d.order={},f=d.options,j=0;j<f.length;j++)g[f[j].key]=j;if(d._original_size&&
d.size==0)d.size=d._original_size,delete d.original_size;d.size>f.length?(d._original_size=d.size,d.size=0):d.size=d._original_size||d.size;b._date&&b._mode==a&&b.setCurrentView(b._date,b._mode)});b.callEvent("onOptionsLoad",[])};b.scrollUnit=function(a){var g=b._props[this._mode];if(g)g.position=Math.min(Math.max(0,g.position+a),g.options.length-g.size),this.update_view()};(function(){var a=function(h){var c=b._props[b._mode];if(c&&c.order&&c.skip_incorrect){for(var a=[],e=0;e<h.length;e++)typeof c.order[h[e][c.map_to]]!=
"undefined"&&a.push(h[e]);h.splice(0,h.length);h.push.apply(h,a)}return h},g=b._pre_render_events_table;b._pre_render_events_table=function(b,c){b=a(b);return g.apply(this,[b,c])};var k=b._pre_render_events_line;b._pre_render_events_line=function(b,c){b=a(b);return k.apply(this,[b,c])};var f=function(h,c){if(h&&typeof h.order[c[h.map_to]]=="undefined"){var a=b,e=864E5,d=Math.floor((c.end_date-a._min_date)/e);c[h.map_to]=h.options[Math.min(d+h.position,h.options.length-1)].key;return!0}},l=b._reset_scale,
m=b.is_visible_events;b.is_visible_events=function(h){var c=m.apply(this,arguments);if(c){var a=b._props[this._mode];if(a&&a.size){var e=a.order[h[a.map_to]];if(e<a.position||e>=a.size+a.position)return!1}}return c};b._reset_scale=function(){var a=b._props[this._mode],c=l.apply(this,arguments);if(a){this._max_date=this.date.add(this._min_date,1,"day");for(var d=this._els.dhx_cal_data[0].childNodes,e=0;e<d.length;e++)d[e].className=d[e].className.replace("_now","");if(a.size&&a.size<a.options.length){var g=
this._els.dhx_cal_header[0],f=document.createElement("DIV");if(a.position)f.className="dhx_cal_prev_button",f.style.cssText="left:1px;top:2px;position:absolute;",f.innerHTML="&nbsp;",g.firstChild.appendChild(f),f.onclick=function(){b.scrollUnit(a.step*-1)};if(a.position+a.size<a.options.length)f=document.createElement("DIV"),f.className="dhx_cal_next_button",f.style.cssText="left:auto; right:0px;top:2px;position:absolute;",f.innerHTML="&nbsp;",g.lastChild.appendChild(f),f.onclick=function(){b.scrollUnit(a.step)}}}return c};
var d=b._get_event_sday;b._get_event_sday=function(a){var c=b._props[this._mode];return c?(f(c,a),c.order[a[c.map_to]]-c.position):d.call(this,a)};var i=b.locate_holder_day;b.locate_holder_day=function(a,c,d){var e=b._props[this._mode];return e&&d?(f(e,d),e.order[d[e.map_to]]*1+(c?1:0)-e.position):i.apply(this,arguments)};var n=b._mouse_coords;b._mouse_coords=function(){var a=b._props[this._mode],c=n.apply(this,arguments);if(a){if(!this._drag_event)this._drag_event={};var d=this._drag_event;if(this._drag_id&&
this._drag_mode)d=this.getEvent(this._drag_id),this._drag_event._dhx_changed=!0;var e=Math.min(c.x+a.position,a.options.length-1),f=a.map_to;c.section=d[f]=a.options[e].key;c.x=0}return c};var j=b._time_order;b._time_order=function(a){var c=b._props[this._mode];c?a.sort(function(b,a){return c.order[b[c.map_to]]>c.order[a[c.map_to]]?1:-1}):j.apply(this,arguments)};b.attachEvent("onEventAdded",function(a,c){if(this._loading)return!0;for(var d in b._props){var e=b._props[d];if(typeof c[e.map_to]=="undefined")c[e.map_to]=
e.options[0].key}return!0});b.attachEvent("onEventCreated",function(a,c){var d=b._props[this._mode];if(d&&c){var e=this.getEvent(a);this._mouse_coords(c);f(d,e);this.event_updated(e)}return!0})})()});
