/*
Copyright DHTMLX LTD. http://www.dhtmlx.com
To use this component please contact sales@dhtmlx.com to obtain license
*/
Scheduler.plugin(function(a){a.config.year_x=4;a.config.year_y=3;a.config.year_mode_name="year";a.xy.year_top=0;a.templates.year_date=function(c){return a.date.date_to_str(a.locale.labels.year_tab+" %Y")(c)};a.templates.year_month=a.date.date_to_str("%F");a.templates.year_scale_date=a.date.date_to_str("%D");a.templates.year_tooltip=function(a,r,o){return o.text};(function(){var c=function(){return a._mode==a.config.year_mode_name};a.dblclick_dhx_month_head=function(a){if(c()){var b=a.target||a.srcElement;
if(b.parentNode.className.indexOf("dhx_before")!=-1||b.parentNode.className.indexOf("dhx_after")!=-1)return!1;var k=this.templates.xml_date(b.parentNode.parentNode.parentNode.parentNode.parentNode.parentNode.getAttribute("date"));k.setDate(parseInt(b.innerHTML,10));var l=this.date.add(k,1,"day");!this.config.readonly&&this.config.dblclick_create&&this.addEventNow(k.valueOf(),l.valueOf(),a)}};var r=a.changeEventId;a.changeEventId=function(){r.apply(this,arguments);c()&&this.year_view(!0)};var o=a.render_data,
w=a.date.date_to_str("%Y/%m/%d"),x=a.date.str_to_date("%Y/%m/%d");a.render_data=function(a){if(!c())return o.apply(this,arguments);for(var b=0;b<a.length;b++)this._year_render_event(a[b])};var y=a.clear_view;a.clear_view=function(){if(!c())return y.apply(this,arguments);for(var a in m)if(m.hasOwnProperty(a)){var b=m[a];b.className="dhx_month_head";b.setAttribute("date","")}m={}};a.hideToolTip=function(){if(this._tooltip)this._tooltip.style.display="none",this._tooltip.date=new Date(9999,1,1)};a.showToolTip=
function(d,b,k,l){if(this._tooltip){if(this._tooltip.date.valueOf()==d.valueOf())return;this._tooltip.innerHTML=""}else{var h=this._tooltip=document.createElement("DIV");h.className="dhx_tooltip";document.body.appendChild(h);h.onclick=a._click.dhx_cal_data}for(var i=this.getEvents(d,this.date.add(d,1,"day")),c="",f=0;f<i.length;f++){var n=i[f],e=n.color?"background:"+n.color+";":"",g=n.textColor?"color:"+n.textColor+";":"";c+="<div class='dhx_tooltip_line' style='"+e+""+g+"' event_id='"+i[f].id+"'>";
c+="<div class='dhx_tooltip_date' style='"+e+""+g+"'>"+(i[f]._timed?this.templates.event_date(i[f].start_date):"")+"</div>";c+="<div class='dhx_event_icon icon_details'>&nbsp;</div>";c+=this.templates.year_tooltip(i[f].start_date,i[f].end_date,i[f])+"</div>"}this._tooltip.style.display="";this._tooltip.style.top="0px";this._tooltip.style.left=document.body.offsetWidth-b.left-this._tooltip.offsetWidth<0?b.left-this._tooltip.offsetWidth+"px":b.left+l.offsetWidth+"px";this._tooltip.date=d;this._tooltip.innerHTML=
c;this._tooltip.style.top=document.body.offsetHeight-b.top-this._tooltip.offsetHeight<0?b.top-this._tooltip.offsetHeight+l.offsetHeight+"px":b.top+"px"};a._init_year_tooltip=function(){dhtmlxEvent(a._els.dhx_cal_data[0],"mouseover",function(d){if(c()){var d=d||event,b=d.target||d.srcElement;if(b.tagName.toLowerCase()=="a")b=b.parentNode;(b.className||"").indexOf("dhx_year_event")!=-1?a.showToolTip(x(b.getAttribute("date")),getOffset(b),d,b):a.hideToolTip()}});this._init_year_tooltip=function(){}};
a.attachEvent("onSchedulerResize",function(){return c()?(this.year_view(!0),!1):!0});a._get_year_cell=function(a){var b=a.getMonth()+12*(a.getFullYear()-this._min_date.getFullYear())-this.week_starts._month,k=this._els.dhx_cal_data[0].childNodes[b],a=this.week_starts[b]+a.getDate()-1;return k.childNodes[2].firstChild.rows[Math.floor(a/7)].cells[a%7].firstChild};var m={};a._mark_year_date=function(a,b){var k=w(a),c=this._get_year_cell(a),h=this.templates.event_class(b.start_date,b.end_date,b);if(!m[k])c.className=
"dhx_month_head dhx_year_event",c.setAttribute("date",k),m[k]=c;c.className+=h?" "+h:""};a._unmark_year_date=function(a){this._get_year_cell(a).className="dhx_month_head"};a._year_render_event=function(a){for(var b=a.start_date,b=b.valueOf()<this._min_date.valueOf()?this._min_date:this.date.date_part(new Date(b));b<a.end_date;)if(this._mark_year_date(b,a),b=this.date.add(b,1,"day"),b.valueOf()>=this._max_date.valueOf())break};a.year_view=function(d){if(d){var b=a.xy.scale_height;a.xy.scale_height=
-1}a._els.dhx_cal_header[0].style.display=d?"none":"";a.set_sizes();if(d)a.xy.scale_height=b;a._table_view=d;if(!this._load_mode||!this._load())if(d){a._init_year_tooltip();a._reset_year_scale();if(a._load_mode&&a._load())return a._render_wait=!0;a.render_view_data()}else a.hideToolTip()};a._reset_year_scale=function(){this._cols=[];this._colsS={};var d=[],b=this._els.dhx_cal_data[0],c=this.config;b.scrollTop=0;b.innerHTML="";var l=Math.floor(parseInt(b.style.width)/c.year_x),h=Math.floor((parseInt(b.style.height)-
a.xy.year_top)/c.year_y);h<190&&(h=190,l=Math.floor((parseInt(b.style.width)-a.xy.scroll_width)/c.year_x));for(var i=l-11,m=0,f=document.createElement("div"),n=this.date.week_start(new Date),e=0;e<7;e++)this._cols[e]=Math.floor(i/(7-e)),this._render_x_header(e,m,n,f),n=this.date.add(n,1,"day"),i-=this._cols[e],m+=this._cols[e];f.lastChild.className+=" dhx_scale_bar_last";for(var g=this.date[this._mode+"_start"](this.date.copy(this._date)),o=g,e=0;e<c.year_y;e++)for(var s=0;s<c.year_x;s++){var j=document.createElement("DIV");
j.style.cssText="position:absolute;";j.setAttribute("date",this.templates.xml_format(g));j.innerHTML="<div class='dhx_year_month'></div><div class='dhx_year_week'>"+f.innerHTML+"</div><div class='dhx_year_body'></div>";j.childNodes[0].innerHTML=this.templates.year_month(g);for(var r=this.date.week_start(g),u=this._reset_month_scale(j.childNodes[2],g,r),p=j.childNodes[2].firstChild.rows,q=p.length;q<6;q++){p[0].parentNode.appendChild(p[0].cloneNode(!0));for(var t=0;t<p[q].childNodes.length;t++)p[q].childNodes[t].className=
"dhx_after",p[q].childNodes[t].firstChild.innerHTML=a.templates.month_day(u),u=a.date.add(u,1,"day")}b.appendChild(j);j.childNodes[1].style.height=j.childNodes[1].childNodes[0].offsetHeight+"px";var v=Math.round((h-190)/2);j.style.marginTop=v+"px";this.set_xy(j,l-10,h-v-10,l*s+5,h*e+5+a.xy.year_top);d[e*c.year_x+s]=(g.getDay()-(this.config.start_on_monday?1:0)+7)%7;g=this.date.add(g,1,"month")}this._els.dhx_cal_date[0].innerHTML=this.templates[this._mode+"_date"](o,g,this._mode);this.week_starts=
d;d._month=o.getMonth();this._min_date=o;this._max_date=g}})()});
