/*
Copyright DHTMLX LTD. http://www.dhtmlx.com
To use this component please contact sales@dhtmlx.com to obtain license
*/
Scheduler.plugin(function(a){(function(){var c=a.dhtmlXTooltip=a.tooltip={};c.config={className:"dhtmlXTooltip tooltip",timeout_to_display:50,delta_x:15,delta_y:-20};c.tooltip=document.createElement("div");c.tooltip.className=c.config.className;c.show=function(e,g){var d=c,m=this.tooltip,b=m.style;d.tooltip.className=d.config.className;var f=this.position(e),h=e.target||e.srcElement;if(!this.isTooltip(h)){var i=0,n=0,j=a._obj;if(j.offsetParent){do i+=j.offsetLeft,n+=j.offsetTop;while(j=j.offsetParent)
}var k=f.x+(d.config.delta_x||0)-i,l=f.y-(d.config.delta_y||0)-n;b.visibility="hidden";b.removeAttribute?(b.removeAttribute("right"),b.removeAttribute("bottom")):(b.removeProperty("right"),b.removeProperty("bottom"));b.left="0";b.top="0";this.tooltip.innerHTML=g;a._obj.appendChild(this.tooltip);var o=this.tooltip.offsetWidth,p=this.tooltip.offsetHeight;a._obj.offsetWidth-k-(a.xy.margin_left||0)-o<0?(b.removeAttribute?b.removeAttribute("left"):b.removeProperty("left"),b.right=a._obj.offsetWidth-k+
2*(d.config.delta_x||0)+"px"):b.left=k<0?f.x+Math.abs(d.config.delta_x||0)+"px":k+"px";a._obj.offsetHeight-l-(a.xy.margin_top||0)-p<0?(b.removeAttribute?b.removeAttribute("top"):b.removeProperty("top"),b.bottom=a._obj.offsetHeight-l-2*(d.config.delta_y||0)+"px"):b.top=l<0?f.y+Math.abs(d.config.delta_y||0)+"px":l+"px";b.visibility="visible"}};c.hide=function(){this.tooltip.parentNode&&this.tooltip.parentNode.removeChild(this.tooltip)};c.delay=function(e,a,d,c){this.tooltip._timeout_id&&window.clearTimeout(this.tooltip._timeout_id);
this.tooltip._timeout_id=setTimeout(function(){var b=e.apply(a,d);e=a=d=null;return b},c||this.config.timeout_to_display)};c.isTooltip=function(e){for(var a=!1;e&&!a;)a=e.className==this.tooltip.className,e=e.parentNode;return a};c.position=function(a){a=a||window.event;if(a.pageX||a.pageY)return{x:a.pageX,y:a.pageY};var c=window._isIE&&document.compatMode!="BackCompat"?document.documentElement:document.body;return{x:a.clientX+c.scrollLeft-c.clientLeft,y:a.clientY+c.scrollTop-c.clientTop}};a.attachEvent("onMouseMove",
function(e,g){var d=window.event||g,m=d.target||d.srcElement,b=c;if(e||b.isTooltip(m)){var f=a.getEvent(e)||a.getEvent(b.tooltip.event_id);if(f){b.tooltip.event_id=f.id;var h=a.templates.tooltip_text(f.start_date,f.end_date,f);if(!h)return b.hide();var i=void 0;_isIE&&(i=document.createEventObject(d));a.callEvent("onBeforeTooltip",[e,f])&&h&&b.delay(b.show,b,[i||d,h])}}else b.delay(b.hide,b,[])});a.attachEvent("onBeforeDrag",function(){c.hide();return!0});a.attachEvent("onEventDeleted",function(){c.hide();
return!0});a.templates.tooltip_date_format=a.date.date_to_str("%Y-%m-%d %H:%i");a.templates.tooltip_text=function(c,g,d){return"<b>Event:</b> "+d.text+"<br/><b>Start date:</b> "+a.templates.tooltip_date_format(c)+"<br/><b>End date:</b> "+a.templates.tooltip_date_format(g)}})()});
