/*
Copyright DHTMLX LTD. http://www.dhtmlx.com
To use this component please contact sales@dhtmlx.com to obtain license
*/
Scheduler.plugin(function(a){a.attachEvent("onTimelineCreated",function(b){if(b.render=="tree")b.y_unit_original=b.y_unit,b.y_unit=a._getArrayToDisplay(b.y_unit_original),a.attachEvent("onOptionsLoadStart",function(){b.y_unit=a._getArrayToDisplay(b.y_unit_original)}),a.form_blocks[b.name]={render:function(a){var d="<div class='dhx_section_timeline' style='overflow: hidden; height: "+a.height+"px'></div>";return d},set_value:function(c,d,f,h){var e=a._getArrayForSelect(a.matrix[h.type].y_unit_original,
h.type);c.innerHTML="";var b=document.createElement("select");c.appendChild(b);for(var i=c.getElementsByTagName("select")[0],k=0;k<e.length;k++){var g=document.createElement("option");g.value=e[k].key;if(g.value==f[a.matrix[h.type].y_property])g.selected=!0;g.innerHTML=e[k].label;i.appendChild(g)}},get_value:function(a){return a.firstChild.value},focus:function(){}}});a.attachEvent("onBeforeViewRender",function(b,c,d){var f={};if(b=="tree"){var h,e,j,i,k,g;c.children?(h=d.folder_dy||d.dy,d.folder_dy&&
!d.section_autoheight&&(j="height:"+d.folder_dy+"px;"),e="dhx_row_folder",i="dhx_matrix_scell folder",k="<div class='dhx_scell_expand'>"+(c.open?"-":"+")+"</div>",g=d.folder_events_available?"dhx_data_table folder_events":"dhx_data_table folder"):(h=d.dy,e="dhx_row_item",i="dhx_matrix_scell item",k="",g="dhx_data_table");td_content="<div class='dhx_scell_level"+c.level+"'>"+k+"<div class='dhx_scell_name'>"+(a.templates[d.name+"_scale_label"](c.key,c.label,c)||c.label)+"</div></div>";f={height:h,style_height:j,
tr_className:e,td_className:i,td_content:td_content,table_className:g}}return f});var l;a.attachEvent("onBeforeEventChanged",function(b,c,d){if(a._isRender("tree")){var f=a.getSection(b[a.matrix[a._mode].y_property]);if(f&&typeof f.children!="undefined"&&!a.matrix[a._mode].folder_events_available)return d||(b[a.matrix[a._mode].y_property]=l),!1}return!0});a.attachEvent("onBeforeDrag",function(b,c,d){if(a._isRender("tree")){var f=a._locate_cell_timeline(d);if(f){var h=a.matrix[a._mode].y_unit[f.y].key;
if(typeof a.matrix[a._mode].y_unit[f.y].children!="undefined"&&!a.matrix[a._mode].folder_events_available)return!1}var e=a.getEvent(b);l=h||e[a.matrix[a._mode].y_property]}return!0});a._getArrayToDisplay=function(b){var c=[],d=function(f,h){for(var e=h||0,b=0;b<f.length;b++){f[b].level=e;if(typeof f[b].children!="undefined"&&typeof f[b].key=="undefined")f[b].key=a.uid();c.push(f[b]);f[b].open&&f[b].children&&d(f[b].children,e+1)}};d(b);return c};a._getArrayForSelect=function(b,c){var d=[],f=function(b){for(var e=
0;e<b.length;e++)a.matrix[c].folder_events_available?d.push(b[e]):typeof b[e].children=="undefined"&&d.push(b[e]),b[e].children&&f(b[e].children,c)};f(b);return d};a._toggleFolderDisplay=function(b,c,d){var f,h=function(a,b,c,d){for(var g=0;g<b.length;g++){if((b[g].key==a||d)&&b[g].children)if(b[g].open=typeof c!="undefined"?c:!b[g].open,f=!0,!d&&f)break;b[g].children&&h(a,b[g].children,c,d)}};h(b,a.matrix[a._mode].y_unit_original,c,d);a.matrix[a._mode].y_unit=a._getArrayToDisplay(a.matrix[a._mode].y_unit_original);
a.callEvent("onOptionsLoad",[])};a.attachEvent("onCellClick",function(b,c){a._isRender("tree")&&(a.matrix[a._mode].folder_events_available||typeof a.matrix[a._mode].y_unit[c].children!="undefined"&&a._toggleFolderDisplay(a.matrix[a._mode].y_unit[c].key))});a.attachEvent("onYScaleClick",function(b,c){a._isRender("tree")&&typeof c.children!="undefined"&&a._toggleFolderDisplay(c.key)});a.getSection=function(b){if(a._isRender("tree")){var c,d=function(a,b){for(var e=0;e<b.length;e++)b[e].key==a&&(c=b[e]),
b[e].children&&d(a,b[e].children)};d(b,a.matrix[a._mode].y_unit_original);return c||null}};a.deleteSection=function(b){if(a._isRender("tree")){var c=!1,d=function(a,b){for(var e=0;e<b.length;e++){b[e].key==a&&(b.splice(e,1),c=!0);if(c)break;b[e].children&&d(a,b[e].children)}};d(b,a.matrix[a._mode].y_unit_original);a.matrix[a._mode].y_unit=a._getArrayToDisplay(a.matrix[a._mode].y_unit_original);a.callEvent("onOptionsLoad",[]);return c}};a.deleteAllSections=function(){if(a._isRender("tree"))a.matrix[a._mode].y_unit_original=
[],a.matrix[a._mode].y_unit=a._getArrayToDisplay(a.matrix[a._mode].y_unit_original),a.callEvent("onOptionsLoad",[])};a.addSection=function(b,c){if(a._isRender("tree")){var d=!1,f=function(a,b,j){if(c)for(var i=0;i<j.length;i++){j[i].key==b&&typeof j[i].children!="undefined"&&(j[i].children.push(a),d=!0);if(d)break;j[i].children&&f(a,b,j[i].children)}else j.push(a),d=!0};f(b,c,a.matrix[a._mode].y_unit_original);a.matrix[a._mode].y_unit=a._getArrayToDisplay(a.matrix[a._mode].y_unit_original);a.callEvent("onOptionsLoad",
[]);return d}};a.openAllSections=function(){a._isRender("tree")&&a._toggleFolderDisplay(1,!0,!0)};a.closeAllSections=function(){a._isRender("tree")&&a._toggleFolderDisplay(1,!1,!0)};a.openSection=function(b){a._isRender("tree")&&a._toggleFolderDisplay(b,!0)};a.closeSection=function(b){a._isRender("tree")&&a._toggleFolderDisplay(b,!1)}});
