/*
Copyright DHTMLX LTD. http://www.dhtmlx.com
To use this component please contact sales@dhtmlx.com to obtain license
*/
Scheduler.plugin(function(a){a.toPDF=function(B,l,u,v){function h(a){return a.replace(newline_regexp,"\n").replace(html_regexp,"")}function n(a){a=parseFloat(a);return isNaN(a)?"auto":100*a/(r+1)}function y(a){a=parseFloat(a);return isNaN(a)?"auto":100*a/o}function w(g){var b="";if(a.matrix&&a.matrix[a._mode]){if(a.matrix[a._mode].second_scale)var c=g[1].childNodes;g=g[0].childNodes}for(var d=0;d<g.length;d++)b+="\n<column><![CDATA["+h(g[d].innerHTML)+"]]\></column>";r=g[0].offsetWidth;if(c)for(var f=
0,e=g[0].offsetWidth,i=1,d=0;d<c.length;d++)b+="\n<column second_scale='"+i+"'><![CDATA["+h(c[d].innerHTML)+"]]\></column>",f+=c[d].offsetWidth,f>=e&&(e+=g[i]?g[i].offsetWidth:0,i++),r=c[0].offsetWidth;return b}function C(g,b){for(var c=parseInt(g.style.left,10),d=0;d<a._cols.length;d++)if(c-=a._cols[d],c<0)return d;return b}function D(g,b){for(var c=parseInt(g.style.top,10),d=0;d<a._colsS.heights.length;d++)if(a._colsS.heights[d]>c)return d;return b}function A(a){for(var b="",c=a.firstChild.rows,
d=0;d<c.length;d++){for(var f=[],e=0;e<c[d].cells.length;e++)f.push(c[d].cells[e].firstChild.innerHTML);b+="\n<row height='"+a.firstChild.rows[d].cells[0].offsetHeight+"'><![CDATA["+h(f.join("|"))+"]]\></row>";o=a.firstChild.rows[0].cells[0].offsetHeight}return b}function E(g){var b="<data profile='"+g+"'";u&&(b+=" header='"+u+"'");v&&(b+=" footer='"+v+"'");b+=">";var c=a._mode;a.matrix&&a.matrix[a._mode]&&(c=a.matrix[a._mode].render=="cell"?"matrix":"timeline");b+="<scale mode='"+c+"' today='"+a._els.dhx_cal_date[0].innerHTML+
"'>";if(a._mode=="week_agenda")for(var d=a._els.dhx_cal_data[0].getElementsByTagName("DIV"),f=0;f<d.length;f++)d[f].className=="dhx_wa_scale_bar"&&(b+="<column>"+h(d[f].innerHTML)+"</column>");else if(a._mode=="agenda"||a._mode=="map")d=a._els.dhx_cal_header[0].childNodes[0].childNodes,b+="<column>"+h(d[0].innerHTML)+"</column><column>"+h(d[1].innerHTML)+"</column>";else if(a._mode=="year"){d=a._els.dhx_cal_data[0].childNodes;for(f=0;f<d.length;f++)b+="<month label='"+h(d[f].childNodes[0].innerHTML)+
"'>",b+=w(d[f].childNodes[1].childNodes),b+=A(d[f].childNodes[2]),b+="</month>"}else{b+="<x>";d=a._els.dhx_cal_header[0].childNodes;b+=w(d);b+="</x>";var e=a._els.dhx_cal_data[0];if(a.matrix&&a.matrix[a._mode]){b+="<y>";for(f=0;f<e.firstChild.rows.length;f++){var i=e.firstChild.rows[f];b+="<row><![CDATA["+h(i.cells[0].innerHTML)+"]]\></row>"}b+="</y>";o=e.firstChild.rows[0].cells[0].offsetHeight}else if(e.firstChild.tagName=="TABLE")b+=A(e);else{for(e=e.childNodes[e.childNodes.length-1];e.className.indexOf("dhx_scale_holder")==
-1;)e=e.previousSibling;e=e.childNodes;b+="<y>";for(f=0;f<e.length;f++)b+="\n<row><![CDATA["+h(e[f].innerHTML)+"]]\></row>";b+="</y>";o=e[0].offsetHeight}}b+="</scale>";return b}function m(a,b){return(window.getComputedStyle?window.getComputedStyle(a,null)[b]:a.currentStyle?a.currentStyle[b]:null)||""}function F(){var g="",b=a._rendered;if(a._mode=="agenda"||a._mode=="map")for(var c=0;c<b.length;c++)g+="<event><head>"+h(b[c].childNodes[0].innerHTML)+"</head><body>"+h(b[c].childNodes[2].innerHTML)+
"</body></event>";else if(a._mode=="week_agenda")for(c=0;c<b.length;c++)g+="<event day='"+b[c].parentNode.getAttribute("day")+"'><body>"+h(b[c].innerHTML)+"</body></event>";else if(a._mode=="year"){b=a.get_visible_events();for(c=0;c<b.length;c++){var d=b[c].start_date;if(d.valueOf()<a._min_date.valueOf())d=a._min_date;for(;d<b[c].end_date;){var f=d.getMonth()+12*(d.getFullYear()-a._min_date.getFullYear())-a.week_starts._month,e=a.week_starts[f]+d.getDate()-1,i=k?m(a._get_year_cell(d),"color"):"",
p=k?m(a._get_year_cell(d),"backgroundColor"):"";g+="<event day='"+e%7+"' week='"+Math.floor(e/7)+"' month='"+f+"' backgroundColor='"+p+"' color='"+i+"'></event>";d=a.date.add(d,1,"day");if(d.valueOf()>=a._max_date.valueOf())break}}}else{var l=a.matrix&&a.matrix[a._mode];if(l&&l.render=="cell"){b=a._els.dhx_cal_data[0].getElementsByTagName("TD");for(c=0;c<b.length;c++)i=k?m(b[c],"color"):"",p=k?m(b[c],"backgroundColor"):"",g+="\n<event><body backgroundColor='"+p+"' color='"+i+"'><![CDATA["+h(b[c].innerHTML)+
"]]\></body></event>"}else for(c=0;c<b.length;c++){var j=n(b[c].style.left),s=n(b[c].style.width);if(!isNaN(s*1)){var t=y(b[c].style.top),r=y(b[c].style.height),q=b[c].className.split(" ")[0].replace("dhx_cal_","");if(q!=="dhx_tooltip_line"){var z=a.getEvent(b[c].getAttribute("event_id")),e=z._sday,x=z._sweek,u=z._length||0;if(a._mode!="month"){if(a.matrix&&a.matrix[a._mode]){var e=0,v=b[c].parentNode.parentNode.parentNode,x=v.rowIndex;s+=n(10)}else{a.xy.menu_width&&(s+=n(s*20/100),j-=n(15-j*20/100));
if(b[c].parentNode==a._els.dhx_cal_data[0])continue;j+=n(b[c].parentNode.style.left);j-=n(51)}if(a.matrix&&a.matrix[a._mode]){var w=o;o=b[c].parentNode.offsetHeight;t=y(b[c].style.top);t-=t*0.2;o=w}}else r=parseInt(b[c].offsetHeight,10),t=parseInt(b[c].style.top,10)-22,e=C(b[c],e),x=D(b[c],x);g+="\n<event week='"+x+"' day='"+e+"' type='"+q+"' x='"+j+"' y='"+t+"' width='"+s+"' height='"+r+"' len='"+u+"'>";q=="event"?(g+="<header><![CDATA["+h(b[c].childNodes[1].innerHTML)+"]]\></header>",i=k?m(b[c].childNodes[2],
"color"):"",p=k?m(b[c].childNodes[2],"backgroundColor"):"",g+="<body backgroundColor='"+p+"' color='"+i+"'><![CDATA["+h(b[c].childNodes[2].innerHTML)+"]]\></body>"):(i=k?m(b[c],"color"):"",p=k?m(b[c],"backgroundColor"):"",g+="<body backgroundColor='"+p+"' color='"+i+"'><![CDATA["+h(b[c].innerHTML)+"]]\></body>");g+="</event>"}}}}return g}function G(){var a="</data>";return a}var r=0,o=0,k=!1;l=="fullcolor"&&(k=!0,l="color");l=l||"color";html_regexp=RegExp("<[^>]*>","g");newline_regexp=RegExp("<br[^>]*>",
"g");var q=(new Date).valueOf(),j=document.createElement("div");j.style.display="none";document.body.appendChild(j);j.innerHTML='<form id="'+q+'" method="post" target="_blank" action="'+B+'" accept-charset="utf-8" enctype="application/x-www-form-urlencoded"><input type="hidden" name="mycoolxmlbody"/> </form>';document.getElementById(q).firstChild.value=encodeURIComponent(E(l).replace("\u2013","-")+F()+G());document.getElementById(q).submit();j.parentNode.removeChild(j);grid=null}});
